### ISSUE TITLE
smooth out streaming output from `draft up`

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#1]
Sometimes, the output from `draft up` can appear somewhat choppy as opposed to a nice flow.

This may or may not be a limitation of websockets. We need to do more research on how we can improve upon our current workflow or if there's a bug in gorilla/websockets we can fix.

**Comment by errordeveloper** [comment]
Is this just a direct one-way stream of plain text messages from the server? Would it make more sense to consider using SSE instead?
And if we do need some two-way communication, may be GRPC over HTTPS would be a good option? 

Also, perhaps build the stages here are quite clear already, and we could consider defining a protocol, such that would turn this from a stream of text into an RPC interaction which would seem like a cleaner design, and could benefit the user by allowing to control output verbosity per build step (e.g. I wanna hide `docker push` section, but still see all the lines that `docker build`  outputs or even some might need to see a trace of Kubernetes API interactions), and potentially allow for the user to invoke the steps manually (e.g. for debugging or GUI wrapper of sorts).

**Comment by errordeveloper** [comment]
> ... potentially allow for the user to invoke the steps manually

This relates to #129.

**Comment by bacongobbler** [comment]
related: #184

**Comment by bacongobbler** [comment]
closed via #237
