### ISSUE TITLE
Add support for custom build hooks

### ISSUE THREAD

**Issue by rodcloutier** [Azure/draft#100]
We would like to be able to have custom build hooks in the `draft up`.
Our use case would be to cross-compile our go application, do some operations, etc. We could then use a scratch container instead of  the `gaoling:onbuild`  image.

**Comment by bacongobbler** [comment]
Helm has the concept of chart hooks which you can use in your chart. Will that work for you?

**Comment by bacongobbler** [comment]
As far as the partial build steps, that already exists in docker but we are waiting on kubernetes to upgrade their supported docker version from v1.12.

**Comment by rodcloutier** [comment]
Yes, something similar to the chart hooks, but run locally, would be interesting.

I was thinking of doing `draft up` but I would be able to call a script that would call my `build` target in the `Makefile`. Maybe we are looking at this wrong but I not convinced that we can move everything out of the dev machine.

The partial build steps might be the solution as we could potentially use containers to do our builds. I will have a look at this in more detail. 

The context of this request is that we are trying to get the CI and developer experience to be as close as possible, sharing some of the scripts or steps. Draft seems to fit the bill on several points on the dev side but we might need some steps that are performed on the dev machine.

**Comment by bacongobbler** [comment]
If you have an implementation you'd like to see in core, I'd be happy to take a look at it.

**Comment by bacongobbler** [comment]
So the idea behind how `draft up` is that it sends a tarballed docker build context and a chart context to the draft server. If you want to do some pre-processing such as a `make` target to produce an image, you can ship that up.

Make the following modifications to your draft.toml locally:

```
build_tar: docker.tar.gz
chart_tar: chart.tar.gz
```

Then you can do the following locally:

```
make generate # assume this generates a bunch of files you want in your docker image into rootfs/
tar -czf docker.tar.gz Dockerfile .dockerignore rootfs/
tar -czf chart.tar.gz chart/
draft up
```

This workflow should allow you to do whatever you wish locally before shipping a final build context to draft.

**Comment by bacongobbler** [comment]
One more thing to note: you can test that the build context works locally by running `docker build - < docker.tar.gz`.

**Comment by bacongobbler** [comment]
I'm closing this as the ask has been solved through uploading a custom docker build context.
