### ISSUE TITLE
Vanilla go project is not detected

### ISSUE THREAD

**Issue by rodcloutier** [Azure/draft#101]
Using a vanilla go project with only a simple `main.go` file results in starter pack not selected.
We currently must have a glide.yaml file.

```
$ mkdir go
$ cd go
$ touch main.go
$ draft create
Error: Unable to select a starter pack Q_Q
$ touch glide.yaml
$ draft create .
--> Go app detected
--> Ready to sail
```

**Comment by bacongobbler** [comment]
i agree that we should check for the presence of a .go extension in the root as well as the glide.yaml (and godeps, dep etc.) that Heroku searches for.

**Comment by rodcloutier** [comment]
Good. Although limited in use, even without a dependency file, we should be able to detect a go project.

**Comment by bacongobbler** [comment]
Gonna wait until after #108 is merged before making this change.

**Comment by technosophos** [comment]
Okay, you should be unblocked now.
