### ISSUE TITLE
question: what's the relationship between this project and Azure/draft-classic

### ISSUE THREAD

**Issue by seeflood** [Azure/draft#104]
what's the relationship between this project and https://github.com/Azure/draft-classic ?

**Comment by imiller31** [comment]
@qpetraroia for viz

**Comment by gambtho** [comment]
draft-classic is the original draft project that was moved to an archived repo (last commit was Feb 2020).   Due to the volume of changes and the different team members we decided to keep that well loved project for historical reasons and have this as a new start
