### ISSUE TITLE
it is trying to push to docker.io/microsoft/...

### ISSUE THREAD

**Issue by errordeveloper** [Azure/draft#106]
Firstly, I wonder if it should bail, or at least complain about default registry being a Microsoft's one (to which I have no access), and tell me what to do...

Secondly, there is clearly more guidance needed around some initial configuration parameters, it's probably in the docs, but I think interactive prompt during `draft init` would work better.

**Comment by bacongobbler** [comment]
Did you follow the steps [here](https://github.com/Azure/draft/blob/master/docs/install.md#configure-draft)? You forgot to change a few parameters through `--set`.

**Comment by bacongobbler** [comment]
Your second point is being addressed in https://github.com/Azure/draft/issues/49 as well.

**Comment by errordeveloper** [comment]
> Did you follow the steps here?

I didn't at the time when I opened this issues.

However, now I've been trying to set registry auth of the past hour with no luck – I don't even know where do I need to look to debug this...

I am glad to hear this is being addressed.
