### ISSUE TITLE
there should draft up once without watching for changes

### ISSUE THREAD

**Issue by errordeveloper** [Azure/draft#107]
I'd like to be able to build and deploy my app as one off, without having to use more then one shell, e.g. something like `draft up --single-shot`  or `draft up --no-watch` or `draft up --once` or even `draft once`.

**Comment by bacongobbler** [comment]
You can disable the watch functionality by flipping `watch` to false in draft.toml. That will give you the single-shot functionality. It's just enabled by default.

**Comment by bacongobbler** [comment]
See the [User Guide](https://github.com/Azure/draft/blob/master/docs/user-guide.md) for more context on the parameters available in draft.toml.

**Comment by errordeveloper** [comment]
Ok, but I don't think editing config file is good UX, flag would be more convenient.

**Comment by bacongobbler** [comment]
I intentionally left out feature flags for the pre-production release so we don't have two conflicting places to set feature flags, but point noted.
