### ISSUE TITLE
Add a logical architecture diagram for Draft

### ISSUE THREAD

**Issue by mekenthompson** [Azure/draft#109]
This would be useful to understand what is happening when Draft is in use, where Docker builds are happening, etc. This would both be technically useful and better demonstrate the use case benefits (ie. not requiring Docker on the developers machine). It would also be useful to include what communications ports/protocols are used.

**Comment by bacongobbler** [comment]
This would be good to explain in the [design doc](https://github.com/Azure/draft/blob/master/docs/design.md).
