### ISSUE TITLE
pull secret should get update when it changes

### ISSUE THREAD

**Issue by errordeveloper** [Azure/draft#111]
Right now we only create it and the way to get it updated is by deleting it and redeploying the app, but daemon config change won't trigger it and it's not quite obvious what's going on.

**Comment by errordeveloper** [comment]
I'd be happy to open a PR, if folks agree with the motivation.

**Comment by bacongobbler** [comment]
This would need to be something fixed upstream. We are performing a `helm upgrade` during the upgrade process which calls `kubectl apply` on the templates, iirc. This won't be something that can be fixed within draft per se.

**Comment by errordeveloper** [comment]
From reading the code I was under impression that pull secret was created
in a procedural manner...

**Comment by bacongobbler** [comment]
Oh! You mean the pull secret we deploy along with the app. I misunderstood. If you feel like taking a crack at a PR, that sounds good to me!
