### ISSUE TITLE
Where is the Draft selection menu when right clicked?

### ISSUE THREAD

**Issue by scheung38** [Azure/draft#119]
Not sure which extension is needed to get Draft selection menu when right click VSCode explorer?

Is this not available yet?

![Screenshot 2022-07-17 at 00 38 03](https://user-images.githubusercontent.com/1273014/179375179-158df7c8-3c9a-4b6d-b2b8-551d2023b20a.png)

Mac OSX 12.4
VSCode: 1.69.1

**Comment by karenychen** [comment]
Hey @scheung38,

We have just released our initial version of the VSCode extension [here](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.aks-devx-tools). Feel free to download and try it out :)

**Comment by scheung38** [comment]
When working with Draft :

1. Do I need to provide my own Ingress as defined in my docker-compose file which has app (Django), NoSQL (MongoDB) and Ingress (Traefik)
This will be converted into K8s manifests via kompose and I think it should go into a folder called manifests. 

2. If working with docker-compose and Dockerfiles are already present, so they need to be at root level?

3. Does it work with any other repo other than GitHub as I have current repo in Bitbucket

**Comment by qpetraroia** [comment]
Hey @scheung38, 

A couple of questions on my end first. Are you saying that you already have a containerized application via docker-compose? 

Regarding this question **Does it work with any other repo other than GitHub as I have current repo in Bitbucket**. Draft only works with GitHub.

Thank you!

**Comment by scheung38** [comment]
Yes it was created from cookiecutter-django so these are the existing files:

docker-compose file: production.yml
kompose-generated folder: k8s manifests

compose/production/django/Dockerfile
compose/production/traefik/Dockerfile
compose/production/mongo/Dockerfile

![Screenshot 2022-07-26 at 22 59 41](https://user-images.githubusercontent.com/1273014/181119798-97639576-d202-41a0-80ef-70a620cc8aaa.png)

**Comment by imiller31** [comment]
@scheung38 can you try just `MyOrganization/MyRepo`

**Comment by scheung38** [comment]
Yes already did as above but still not found but got remote -v shows it is there
