### ISSUE TITLE
Error: error when upgrading: rpc error: code = Unknown desc = YAML parse error on draftd/templates/deployment.yaml

### ISSUE THREAD

**Issue by berndverst** [Azure/draft#122]
Receiving the following error when trying to init or upgrade.

```
Error: error when upgrading: rpc error: code = Unknown desc = YAML parse error on draftd/templates/deployment.yaml: error converting YAML to JSON: yaml: line 25: could not find expected ':'
```

```
draft init --set registry.url=draftregistry.azurecr.io,registry.org=draftregistry,registry.authtoken=$authtoken,basedomain=draft.readon.ly --upgrade
Creating pack golang
Creating pack php
Creating pack node
Creating pack java
Creating pack ruby
Creating pack python
$DRAFT_HOME has been configured at /Users/bverst/.draft.
Error: error when upgrading: rpc error: code = Unknown desc = YAML parse error on draftd/templates/deployment.yaml: error converting YAML to JSON: yaml: line 25: could not find expected ':'
```

```
Client: &version.Version{SemVer:"canary", GitCommit:"ed93463b23f1ebb5ee6f670b6dbbb51df11aa46e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary", GitCommit:"34f37fd12ce5d020867a40c8baeb83cb02286579", GitTreeState:"dirty"}
```

**Comment by rodcloutier** [comment]
Can't seem to reproduce this. What os are you running? Are you working from source? Are you up to date on your git repo?

**Comment by berndverst** [comment]
I was able to fix it.

So turns out that this can happen when you specify an invalid authtoken (not sure if it was malformed or just not authorized) for your container registry. [I use Azure Container Registry]

**Comment by bacongobbler** [comment]
most likely malformed since this was during `draft init`, which is essentially a call to `helm install`. The chart doesn't do any validation on whether the auth token is authorized.

Were there newline characters in your base64-encoded string? Perhaps we should document to use it with `-w=0` to prevent newline characters on longer auth token JSON strings for now.

**Comment by bacongobbler** [comment]
Ah now I remember why I never documented that feature flag... It doesn't exist in macOS Sierra unless you install gnu-base64 from homebrew.
