### ISSUE TITLE
Basedomain option ignored during draft init / upgrade ?

### ISSUE THREAD

**Issue by jcorioland** [Azure/draft#127]
Hi

The **basedomain** option seems to be ignored during draft init --set / --upgrade.

**Helm & Draft versions I am running:**

```
jcorioland@DESKTOP-DGKT17J:~/projects/draft/examples/nodejs$ helm version
Client: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.2", GitCommit:"82d8e9498d96535cc6787a6a9194a76161d29b4c", GitTreeState:"clean"}
jcorioland@DESKTOP-DGKT17J:~/projects/draft/examples/nodejs$ draft version
Client: &version.Version{SemVer:"canary", GitCommit:"34f37fd12ce5d020867a40c8baeb83cb02286579", GitTreeState:"clean"}
Server: &version.Version{SemVer:"canary", GitCommit:"34f37fd12ce5d020867a40c8baeb83cb02286579", GitTreeState:"dirty"}
```

**Draft init command:**

`draft init --set registry.url=draftjco.azurecr.io,registry.org=draftjco,registry.authtoken=AUTH_TOKEN,basedomain=draft.juliencorioland.net`

When I do a draft up, everything goes fine:

- The Dockerfile is generated
- The image is built
- The image is pushed into the ACR
- The application is deployed (everything is ok in the k8s deployment/pods)

But:
- The output URL is http://affable-sabertooth.example.com and not http://affable-sabertooth.draft.juliencorioland.net 
-  And of course, The application is not available on http://affable-sabertooth.draft.juliencorioland.net.

Thanks
Julien

**Comment by squillace** [comment]
First, read https://github.com/Azure/draft/issues/89#issuecomment-306567545 and see if the repair steps don't solve your problem. There is an open issue on making the "fix the base domain config" a bit easier.

**Comment by bacongobbler** [comment]
I'm just standing up my cluster as well now, so once that's up I can give this a shot too and see if I can confirm this. I have a faint feeling that #110 might have broken things unintentionally.

**Comment by bacongobbler** [comment]
I am seeing this too in master. Lemme try reverting #110 locally and see if that fixes things.

**Comment by ams0** [comment]
I have the same behavior. And inspecting my draftd deployment reports the correct value for basedomain:

```
$ k describe deploy draftd  --namespace=kube-system
Name:			draftd
Namespace:		kube-system
CreationTimestamp:	Thu, 08 Jun 2017 18:09:42 +0200
Labels:			chart=draftd-canary
Annotations:		deployment.kubernetes.io/revision=1
Selector:		app=draft,name=draftd
Replicas:		3 desired | 3 updated | 3 total | 3 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Pod Template:
  Labels:	app=draft
		name=draftd
  Containers:
   draftd:
    Image:	docker.io/microsoft/draft:canary
    Port:	44135/TCP
    Args:
      start
      --registry-url=msdxnl.azurecr.io
      --registry-org=microsoft
      --registry-auth=<redacted>
      --basedomain=apps.alessandrovozza.com
    Liveness:	http-get http://:44135/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:	http-get http://:44135/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DRAFT_NAMESPACE:	 (v1:metadata.namespace)
    Mounts:
      /var/run/docker.sock from docker-socket (rw)
  Volumes:
   docker-socket:
    Type:	HostPath (bare host directory volume)
    Path:	/var/run/docker.sock
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
OldReplicaSets:	<none>
NewReplicaSet:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  23m		23m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled up replica set draftd-807761545 to 3
```

**Comment by bacongobbler** [comment]
Removing the `basedomain` field from the values.yaml in my repo fixed it on the next deploy (delete and upload, ingress doesn't support upgrades right now). I'll file a PR to revert that commit.

**Comment by ams0** [comment]
The culprit is that the ```draft init``` command does populate $HOME/.draft/packs ignoring the _basedomain_ specified; I manually change $HOME/.draft/packs/<lang>/chart/values.yaml after ```draft init```, then ```draft create``` and it's working now. Thanks for the pointers!

**Comment by bacongobbler** [comment]
Yep, that's the same conclusion I came to. #128 is the PR that fixes this. :)

**Comment by squillace** [comment]
Excellent. :-) :+1:

**Comment by jcorioland** [comment]
Same here. It is working after updating the values.yaml as @ams0 suggested. :)

**Comment by ams0** [comment]
If I may suggest, part of the confusion come from the difference in the meaning of ```init```between helm and draft: in the former, ```init``` interacts with the remote cluster (setting Tiller up), while in draft, it's pretty much a local affair (setting $HOME/.draft folder). Am I wrong? Moreover, while you ```helm init``` once per Kubernetes cluster, you could potentially (as far as my understanding of draft) issue a  ```draft init``` multiple times in the same context (in the Kubernetes meaning), if you want to publish multiple applications over multiple basedomains. My 0.0000072 BTC :)

**Comment by bacongobbler** [comment]
> Am I wrong?

Slightly. `draft init` also interacts with the remote cluster, setting draftd up.
