### ISSUE TITLE
Use yarn instead of npm

### ISSUE THREAD

**Issue by newtack** [Azure/draft#148]
I may be mistaken but it looked like draft is using npm, which is 5-10 times slower than yarn. Can you either default to using yarn for node js packagement management or at a minimum offer an option of using yarn instead of npm?

**Comment by bacongobbler** [comment]
Given that the majority of the node.js community is still using npm I'd still prefer to use that by default if it's just a matter of performance. If yarn ever becomes 1.0 and is generally accepted by the node.js community at large then we could consider changing the default pack to use yarn.

However, after you call `draft create` you can happily change the default Dockerfile to use whatever package manager you choose. You're not "locked in" to a certain workflow with Draft. In fact you should be committing your chart and Dockerfile to git and continue to hack on those after you've initially called `draft create` to further improve upon it.

**Comment by newtack** [comment]
Makes sense, thanks for the fast reply.
