### ISSUE TITLE
use docker-in-docker instead of mounting the host docker daemon socket

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#150]
This allows us to ship a version of Docker separate to Kubernetes, allowing us to write multi-stage images like in #142. I feel like this is a safe change because we only care about the build capabilities of the engine as opposed to Kubernetes being concerned about the runtime capabilities. It should be fine as long as the docker image format is backwards compatible.

**Comment by frodopwns** [comment]
I can take this on!

**Comment by frodopwns** [comment]
PR #163
