### ISSUE TITLE
Make draft init foolproof

### ISSUE THREAD

**Issue by sgoings** [Azure/draft#152]
Requiring users to copy/paste/change this line:

```
draft init --set registry.url=changeme,registry.org=changeme,registry.authtoken=changeme,basedomain=changeme
```

has caused some false starts and pain for first timers.

What could be done to make `draft init` be able to successfully install draft on a kubernetes cluster without any intense documentation parsing?

**Comment by sgoings** [comment]
One idea I had was to make `draft init` an interactive prompt. If the user hasn't specified all of the required options (from the commandline, from a config file, from environment variables)... could the draft client start asking questions of the user? Such as:

```
What registry would you like to use? [dockerhub]
<enter>

What registry would you like to use? [1]
1) Dockerhub
2) Quay.io
3) Google Container Registry
4) Azure Container Registry
...
<enter>

What's your registry username? [default to $USER]
sgoings<enter>

What's your registry password?
*****<enter>
...
```
and so on.

**Comment by bacongobbler** [comment]
> If the user hasn't specified all of the required options (from the commandline, from a config file, from environment variables)... could the draft client start asking questions of the user? Such as:

Bingo. This is exactly how I want to solve it. However, I want to make the prompt a little smarter by reading from the local kube config.

For example, if the current context is found to be a minikube cluster (easily identifiable as the config's name would be "minikube), then we can make the following assumptions:

```
$ draft init
It looks like you are using a Minikube cluster. Is this correct? (Y/n) y
Awesome! Checking to see if plugins "ingress" and "registry" are installed... (GOOD)
Checking to see if tiller is installed... (GOOD)
Draftd (the Draft server side component) has been installed into your Kubernetes Cluster.
Happy Sailing!
```

So then the user workflow for installing draft looks like this:

```
$ minikube addons install ingress
$ minikube addons install registry
$ minikube start
$ helm init
$ draft init
```

If the user answers "no" to the original question, then we go through the prompt you mention.

A lot of chicken-scratch discussion is talked about in #49 but this ticket seems to be a much clearer discussion on how we want to tackle this problem, so I'll make this the official "draft init overhaul discussion" ticket.

**Comment by bacongobbler** [comment]
Progress ongoing at https://github.com/bacongobbler/draft/tree/draft-init-rewrite
