### ISSUE TITLE
draft init requires email, although it's not really needed by the OSS registry

### ISSUE THREAD

**Issue by SteveLasker** [Azure/draft#167]
When following: https://github.com/Azure/draft/blob/master/docs/install.md I see the command
```
$ echo '{"username":"jdoe","password":"secret","email":"jdoe@acme.com"}' | base64
```
Knowing registries don't actually require email, I just took it off. After a 'draft up' I got the error:
```Error encountered streaming JSON response: no basic auth credentials```
It took a while to even get this far, as CLIs don't apparently do auto-correct :(. So, it took a bit more to make sure the username/password combination were proper and just happen to try adding the email.
Based on the refactor, I see this encoding may go away, which would be perfect. But, I would imagine there'd be a CLI that still took --username --password, and just suggesting we remove any dependency for the user to pass in email. 
Was going to do a PR for the docs to note this requirement until the refactoring is done, but I believe the change is quickly pending.

**Comment by bacongobbler** [comment]
This is actually going completely away in #154. We only ask for the user's username and password.
