### ISSUE TITLE
implement a draft plugin manager

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#185]
Similar to helm's plugin manager, we should have a plugin manager for draft to install and remove plugins.

The bare minimum would be to just be able to install and remove plugins, but in the future I'd love to see upgrades, searching, and notifications that updates are available within the plugin system.

**Comment by bacongobbler** [comment]
Perhaps one of the targets we can try to test coming out the door with this feature is the in-progress [draft-packs](https://github.com/rodcloutier/draft-packs) plugin @rodcloutier has been working on.

**Comment by bacongobbler** [comment]
@michelleN does this look good to close now that `draft plugin list/install/remove` have been implemented, or is there more work to be done on this front?

**Comment by michelleN** [comment]
This work is complete so closing this issue.
