### ISSUE TITLE
draft init cannot be used in unattended scripts

### ISSUE THREAD

**Issue by alexpilotti** [Azure/draft#191]
Commit https://github.com/Azure/draft/commit/c06bafac2538a2ca2a7c0c78e88c1484340c9a60 removed the --set CLI option and it is not possible anymore to set the Docker registry and the Ingress base domain in an unattended automated way.

**Comment by squillace** [comment]
I would have thought we'd retain the `--set` switch (or similar properties) for anyone who knows what they want to do. If it's not `--set`, it should be something. :-)

**Comment by bacongobbler** [comment]
Advanced users can use `helm install`, which is exactly what `draft init` does anyways. They'll just need to fend for themselves for the time being until we can come up with a better overall init system that encompasses most cloud providers.

**Comment by alexpilotti** [comment]
Would it make sense to add an usage sample in the documentation using helm install?
I think it would be useful for people looking at more advanced use cases, especially for those not very familiar with helm yet.

**Comment by squillace** [comment]
+1. Problem here is that new users do not necessarily know what draft is and is not using helm for, whereas "advanced users" will already understand this. So how to do this has to be documented _somewhere_. :-)

**Comment by alexpilotti** [comment]
There are also new users not familiar with draft / helm with "advanced" use cases: e.g. setting a custom Docker registry or an ingress base domain.

**Comment by bacongobbler** [comment]
With the proposed solution in #202, we envision a bundled .msi that would install minikube, the in-cluster registry, ingress, helm and draft on the cluster. That would cover the 90th percentile of users that just want to start writing applications for kubernetes. In those use cases, no unattended scripting would be necessary.

For advanced uses cases that encompass a certain cloud provider or some form of CI automation (the 10th percentile), we still haven't come up with a solid solution yet. It might involve publishing official chart releases of draft along with a set of documentation for the time being, but I'd also like to get a solid answer for "how do I get this running on Azure". Right now it's not clear what is the best path forward.

**Comment by squillace** [comment]
Let us all chew.

**Comment by bacongobbler** [comment]
Reposting a response I posted on an email thread a few weeks ago:

> Adding on to why `--set` was removed...

> Nobody should have to learn how Docker handles authentication against registries at a low level. Many users were having trouble and it made for a horrible Out of the Box experience. At least we’re at a state where most users can install Draft without falling on their own two feet ;)

> Right now, I want to leave `draft init` as it is and focus on the developer experience side of things (what Draft is actually trying to solve). I’m hoping that either the community will come up with a better solution than we can, or that we eventually solve the problem in the future (but before v1.0). That being said, we are still actively thinking of ways on how we can improve the installation experience.

**Comment by pyronicide** [comment]
As the draftd chart is embedded in install.go, I couldn't find a repeatable way to use helm install. Instead, here's a very simple script that just fills out `draft init` in an unattended way.

https://gist.github.com/pyronicide/9cd7e92c448f529ec15808d404cb16b8

**Comment by bacongobbler** [comment]
@pyronicide the draft chart is also available in the source code: https://github.com/Azure/draft/tree/master/chart

**Comment by bacongobbler** [comment]
Also @pyronicide that is exactly the example I was looking for, so thank you! It is possible to use `draft init` in unattended scripts so long as you pipe in the values through stdin.

**Comment by pyronicide** [comment]
@bacongobbler totally! I just get scared when I see something in code *and* somewhere else (if only because I consistently forget to update things in two places). My other, larger, problem is that I'm lazy and wanted the chart hosted in a repo somewhere =)

**Comment by bacongobbler** [comment]
We already use go-bindata to auto-generate the go code for packs, so we might be able to apply the same practice for the chart installer. I'l file a ticket to track that. Regardless nice work! 👍

**Comment by bacongobbler** [comment]
closing as there have been a few proposed solutions here.
