### ISSUE TITLE
implement a `draft packs` manager plugin

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#2]
For `draft` to work in a large organization, there needs to be a mechanism to acquire and update a standard set of packs. Developers need to ensure they are using the same set of possibly team-specific language packs and charts.

This would mean:

 - remove pack initialization from `draft init`
 - implement a `draft-packs` plugin to fetch, update and otherwise manage installed packs
 - implement a pack server to serve these packs

**Comment by bacongobbler** [comment]
This got accidentally closed.

**Comment by sgoings** [comment]
I've had a few conversations with people and it seems like a good idea might be to port helm's plugin installer into draft for this purpose: https://github.com/kubernetes/helm/blob/master/pkg/plugin/installer/installer.go

**Comment by rodcloutier** [comment]
I see that the plugin installer is already ported. Maybe we could be inspired by Helm and have some of the same concepts? It would maybe make it easier to adopt the technology and move from one tool to the other since they are closely linked.

# Pack management

So we would need operation on packs (package, verify, etc.) Maybe something like:
```
$ draft pack package
$ draft pack verify
```
# Server
Maybe we could have something similar to helm with a simple http server that would server an index.yaml with link to archives containing the pack.

Maybe introduce the notion of repo, as with helm:
```
$ draft repo add <url>
$ draft repo update
```

Any thoughts on this?

**Comment by bacongobbler** [comment]
I think @technosophos already has his teeth sunk into this feature, but yes, that's how we envisioned this feature.

**Comment by rodcloutier** [comment]
Good. 
@technosophos, if you need help with some tasks or testing, I would be more that willing to help!

**Comment by bacongobbler** [comment]
Actually I was wrong on that assumption. Feel free to take this PR if you feel like working on it, otherwise myself or someone from the Azure team will pick up on this within the next month or so tops. :)

**Comment by rodcloutier** [comment]
Good, I started working on this. Should it really be a plugin? Could you fill me in on the direction regarding plugins architecture of Draft?

 It seems to be core to draft and Helm brought this functionality as embedded commands. I will put up a tentative pull request with the same approach. Feel free to comment.

**Comment by bacongobbler** [comment]
One name stuck out above all the rest for this feature... In order to differentiate the scope and feature set of this plugin vs. #287, we thought `draft pack-man` would be an AWESOME name.

We're still ironing out the user/developer experience at this time, but a pack manager is still on the roadmap before we release v1.0.0.

**Comment by bacongobbler** [comment]
Development is ongoing at https://github.com/Azure/draft-pack-repo.
