### ISSUE TITLE
figure out upgrade story for draftd

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#202]
To upgrade draftd in the kubernetes cluster, I run a `helm delete draft --purge` and re-run init.
One option is to fix the `--upgrade` flag on `draft init`
Another option (more temp but maybe slightly better than what we have now) is to push draft to the kubernetes charts repo or its own repo and push updated draft charts there so a user could do a `helm upgrade draft stable/draft` instead of the delete and purge step.

**Comment by bacongobbler** [comment]
Additional pain point:

@squillace was wanting to figure out how to upgrade from v0.5.0 to the eventual v0.5.1 release. He was sad to hear that the only upgrade path for now is to `helm delete --purge draft` and re-run `draft init`. So I'm here adding another +1 to the tire fire on behalf of @squillace. :)

**Comment by bacongobbler** [comment]
I'm all for the `helm install/helm upgrade` story myself. My open questions for that are:

1) How do we avoid the docker base64-encoded auth token (eww)
2) How do we get the registry URL for minikube? Do we grab `$REGISTRY_SERVICE_HOST:$REGISTRY_SERVICE_PORT` from the environment and assume that?

I'd love to go the Helm route, but I'd also love a really smooth and painless install/upgrade story, too. :)

**Comment by KylieLiang** [comment]
Happy to have a upgrade option. And it is better to add a step to copy draft to system binary folder instead of asking end user do the 'cp' or 'mv'. Of course, it is better to ask end user key in the path and show the default path as /usr/local/bin.

**Comment by bacongobbler** [comment]
We're playing around with the idea of packaging up several projects including Draft in a nicely bundled .msi, .pkg and .deb at some point, so eventually that step to copy Draft off to a directory on your $PATH will eventually go away with that idea.

**Comment by bacongobbler** [comment]
@KylieLiang to ensure we don't lose track of this discussion, would you mind opening a new ticket to discuss the client installation instructions and how we can improve the experience? It is good feedback but it isn't directly relevant to "upgrading draftd".

For clarification, draftd is the server. Draft is the client.

**Comment by kyliel** [comment]
Thank you reply. Sure, let me open a new one ticket for experience for draft client. 

BTW, I failed to log in my account KylieLiang. This is my new GitHub account. I will use this one account to create a ticket.

**Comment by alexpilotti** [comment]
For automating the installation of Minikube, steps are really simple and can be handled with a simple powershell script, e.g.: https://github.com/cloudbase/VSKubernetes/blob/master/VSKubernetes/Binaries/DeployMinikube.ps1

The action performed in PowerShell can become custom actions in an MSI for those who don't like PowerShell.

**Comment by squillace** [comment]
I wrote novels, until I came to the decision that it's really a draftd thing and not a draft thing. create a draftd chart (note, D! (you're not installing draft)), and then helm upgrade draft/draftd makes complete sense, along with helm delete --purge. Whatchya think?

**Comment by michelleN** [comment]
yep that makes sense @squillace.

**Comment by bacongobbler** [comment]
#373 fixes this in a blunt way: we always run `helm delete --purge draft` on every call to `draft init` so to ensure that the requested version of draftd is always installed. Feedback welcome!
