### ISSUE TITLE
Bash plugins can't take user input

### ISSUE THREAD

**Issue by emperorcezar** [Azure/draft#206]
I'm writing a plugin to bootstrap our environment. Part of the process is taking user input with the bash `read` function. Seems that I can do this when it is run as a plugin. The script immediately exits. I noticed the same on before when running `draft init` as part of the plugin. When draft asks it's Y/N question it just exits out with error.

**Comment by bacongobbler** [comment]
> noticed the same on before when running draft init as part of the plugin. When draft asks it's Y/N question it just exits out with error.

I'm pretty sure this was fixed in https://github.com/Azure/draft/pull/177. Which version of draft are you running?

The meat and potatoes of this request is a good proposal, though. I was able to replicate this via

```
><> cat ~/.draft/plugins/draft-hi/plugin.yaml 
name: "hi"
version: "0.1.0"
usage: "reads name and greets the user"
description: |-
  reads name from stdin and greets the user back
ignoreFlags: false
useTunnel: false
command: "$DRAFT_PLUGIN_DIR/plugin.sh"

><> cat ~/.draft/plugins/draft-hi/plugin.sh 
#!/usr/bin/env bash

echo "What is your name?"
read name
echo "Hi $name!"
```

Output:

```
><> draft hi
What is your name?
Hi !
```

A nice greeting for sure, but not what was expected. :)

**Comment by bacongobbler** [comment]
Marking as an enhancement proposal for plugins to accept input streams from STDIN.
