### ISSUE TITLE
draft up fails with capitals in application name

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#209]
When deploying using `draft up` with a CamelCase name (or just a name with capitals in general), draft fails with the following:

```
$ draft up
--> Building Dockerfile
Could not build image from build context: Error response from daemon: invalid reference format: repository name must be lowercase
```

We either need to cast the name to lowercase to work around this limitation of docker image name formats or enforce it.

**Comment by bnookala** [comment]
@bacongobbler 👋  I'd like to try my hand at taking this on, if that's cool! I was thinking that it would be least intrusive to auto-lowercase the name when creating the application? Perhaps with an info message alerting the user that this was happening due to docker's limitation?
