### ISSUE TITLE
vote: disable watch feature by default

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#210]
When writing real apps (like draft itself), the first thing I tend to do is disable the watch feature because I *constantly* save half-baked code while I'm writing. This causes `draft up` to fail, and in the case of calling `draft up` on Draft itself, we can deploy broken code we did not intend to release, which then future `draft up` calls will just break entirely. This is why [watch is disabled for draft itself](https://github.com/Azure/draft/blob/master/draft.toml#L6).

This ticket is to track interest on whether people using draft find the watch feature actually useful for their use case, or if they think it's just a cool party trick that gets in the way.

A vote up (to disable the watch feature by default) or a vote down (to keep it the way it is) should suffice for a vote, but if you have additional context or feel like debating the discussion, feel free to comment below!

**Comment by squillace** [comment]
@bacongobbler one thing to note is that the "go deploy this to test in some way" feature is F5 in VS; means, "start in debug". So, ignoring the IDE for a moment that you happen to be using for dev, you'd want to be able to "trigger" a deploy. Basically, I'd expect `draft up` to deploy; `draft up --watch` to deploy and watch.

**Comment by technosophos** [comment]
I love being able to do --watch during my debug cycle. But when I'm actively coding new features, it's a bit burdensome (esp. since I do my dev work on Azure ACS, rather than local). Also, to get the best VS Code extension experience, I tend to tell users to disable watch. So, I guess I'd rather it disabled by default.
