### ISSUE TITLE
authenticate against docker registry on `draft init`?

### ISSUE THREAD

**Issue by squillace** [Azure/draft#213]
env: Azure Cloud Shell (Ubuntu 16.04)
Draft: 0.5.1
Helm: 2.5
Kubectl: 
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z",
GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z",
GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

Experience: 
draft --debug up gives:

```
 ---> b2e973c8c32e
Successfully built b2e973c8c32e
Successfully tagged bucket-microsoft.azurecr.io/bucket-microsoft/brawny-panda:dad28aeb9d351a00d2804b7dfda4285043789805
--> Pushing bucket-microsoft.azurecr.io/bucket-microsoft/brawny-panda:dad28aeb9d351a00d2804b7dfda4285043789805
The push refers to a repository [bucket-microsoft.azurecr.io/bucket-microsoft/brawny-panda]
ae943f533244: Preparing
2238e2393893: Preparing
ed7b605dc18c: Preparing
59d131791a5d: Preparing
be9cbeee35e4: Preparing
3b783483463c: Preparing
7f5c5258f618: Preparing
d9ac75d7d160: Preparing
19a735fbad89: Preparing
5fada12c27a7: Preparing
a420442c7891: Preparing
e4dafb7385d0: Preparing
e9c375282580: Preparing
dcd61d2ac531: Preparing
71ce2dc7f761: Preparing
0d960f1d4fba: Preparing
Error encountered streaming JSON response: no basic auth credentials
Watching local files for changes...
DEBU[0000] NOTIFY PATH: /home/ralph/draft/examples/dotnetcore/...
```

Expectation: `--debug` should have given some sort of hint where, precisely, this cred issue occurred, and which creds are mistaken or, _especially_, missing (if that's the case).

**Comment by bacongobbler** [comment]
So one thing I found where this issue comes up is when the admin user is disabled for an Azure container registry. In that situation, no matter what you enter into the username and password parameters, you'll never be able to log in unless you happen to be on a node that has a service principal identity. Because we are running docker inside a container, it does not have knowledge of this service principal.

I found that by enabling the admin account via

```
az acr update -n myregistry --admin-enabled true
```

Then using one of the passwords shown in

```
az acr credential show -n myregistry
```

Allowed me to push to the registry.

Tack on another +1 to authenticating against the registry via `draft init`.

**Comment by bacongobbler** [comment]
> Tack on another +1 to authenticating against the registry via draft init.

One edge case that we may want to consider with this feature: what if the registry credentials we are supplying to the draft server only work for the cluster we are running? For example, a private registry locked down within a private cloud. The user running `draft init` may not be able to reach the registry, but the cluster that draftd is being installed into would.

How about we add a health check to the draft server's startup, and make `draft init` wait for the server to come up. If the service fails, then we can report it failed along with perhaps some better idea on why it crashed.

**Comment by squillace** [comment]
I'm loathe to wait too long simply to start initialization. I would imagine we _could_ wait if the user requests it: `--wait-on-validation` or something.

**Comment by bacongobbler** [comment]
This should no longer be necessary now that `docker push` should tell you to log in, but if not then perhaps #306 might be a good way to solve this.
