### ISSUE TITLE
Improve the installation experience of draft

### ISSUE THREAD

**Issue by kyliel** [Azure/draft#222]
It is better to add a step to copy draft to system binary folder instead of asking end user do the 'cp' or 'mv'. Of course, it is better to ask end user key in the path and show the default path as /usr/local/bin.

**Comment by kyliel** [comment]
Attach comment from bacongobbler on the other thread. 
--
We're playing around with the idea of packaging up several projects including Draft in a nicely bundled .msi, .pkg and .deb at some point, so eventually that step to copy Draft off to a directory on your $PATH will eventually go away if that comes to fruition.That may also be our draftd upgrade story... at least if the bundled package also includes minikube and upgrades the components during the .msi installer.

**Comment by bacongobbler** [comment]
I have a work-in-progress homebrew repository that would install Draft, Minikube, Helm and others locally without having to worry about moving the binaries onto your $PATH. This only works for macOS, though. I'm still trying to figure out if it's the right path we want to go, but I figured I'd just bump this ticket and say we are working on it :)

**Comment by bacongobbler** [comment]
I just realized we have a duplicate issue at #161, so I'm closing this in favour of that ticket. Thank you @kyliel!
