### ISSUE TITLE
draft up with `set` fields does not work

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#223]
Given the following draft.toml:

```
[environments]

    [environments.development]
    name = "myapp"
    set = ["ingress.enabled=true"]
```

That value is not set in the resulting chart. I think this appears because `.vals()` [completely ignores the environment's set values](https://github.com/Azure/draft/blob/82eda3d1a9230cd125f683a25d376b7b35f7fd92/cmd/draft/up.go#L96).

**Comment by bacongobbler** [comment]
re-opening as I'm still seeing this in master.

**Comment by santiycr** [comment]
hm, this seems like a big deal to me. Is it right that there's no way to actually pass custom values to the charts via `draft`? I did get to this point after spending hours debugging issues as it seemed based on the docs that `set` was already implemented :/

**Comment by pascaldevink** [comment]
This is a very big deal! The premise of having multiple different environments managed with draft, where environments only differ through environment variables is gone if this doesn't work.

**Comment by squillace** [comment]
Agreed.

**Comment by bacongobbler** [comment]
If anyone has some free time and wants to contribute to Draft, I'm more than happy to point them in the right direction on Slack :) If not we'll get to this before 1.0 is out. This is a fairly severe usability bug. I agree.

**Comment by robertstarmer** [comment]
I think I have some more clarity here.  'set = ["foo=bar"]' works, but only if the value doesn't exist in the chart values.yaml file!  I've been able to set un-defaulted parameters with draft, but it doesn't seem to override the defaults even if the value name is the same.
