### ISSUE TITLE
Can minikube be used with a wildcard domain?

### ISSUE THREAD

**Issue by tstringer** [Azure/draft#238]
I'm not sure if I'm not reading the documentation the right way, but I'm confused if this configuration is possible.

I'd like to use minikube as my target k8s cluster for development. I was attempting to use dnsmasq for ingress, but that was proving to be difficult (it appears as though dnsmasq on my Fedora machine is already up and running with a managed configuration. I haven't investigated what component is currently utilizing dnsmasq which is why I'm exploring other avenues).

Fast-forward, [from the documentation I could use a wildcard domain that I manage](https://github.com/Azure/draft/blob/master/docs/ingress.md#point-a-wildcard-domain). No problem, buy the domain and set the A record. But my question is, could I use a combination of this public wildcard domain with minikube for my local environment?

Thank you in advance, and I'm absolutely loving draft so far. It's proving to be a pleasant dev experience!

P.S. I hope this is a good place to ask this question!

**Comment by bacongobbler** [comment]
Yes, it is completely possible to do so. Just make sure to create your wildcard A record with the result of `minikube ip` and you should be good to go.

**Comment by tstringer** [comment]
Awesome, thank you so much for that super quick verification!! 👍 😄
