### ISSUE TITLE
use go-bindata to autogenerate the chart

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#247]
Right now we have the chart that is installed by `draft init` embedded directly in the code as well as in `chart/`. This means that maintainers need to make changes in two different places, and it has gone out of sync many times. We should use `go-bindata` to autogenerate the go code based on the charts as we do with the draft packs in #108.

blocked by #236 as that will change the directory structure of the chart.

**Comment by squillace** [comment]
@bacongobbler, what is the user's experience of this? Is this an internal thing, or will they see some change as a result?

**Comment by bacongobbler** [comment]
No user experience change, just less code duplication.
