### ISSUE TITLE
release a homebrew formula for Draft

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#250]
In order to make the installation experience for Minikube/Helm/Draft vastly improved, we should release a Homebrew formula for Draft that installs Helm, Minikube and Draft, as well as configures `minikube` properly for a pain-free `minikube start; helm init; draft init` experience.

**Comment by bacongobbler** [comment]
related: #222

**Comment by squillace** [comment]
me like. me want dnsmasq in there, but precisely how and so on....

What are you thinking for optionality? Are we going to prompt for, "do you want us to install the dependencies for you, or would you like to do it all yourself? 

Are we thinking we might detect the existing environment, and THEN make decisions? Whatchya thinking?

**Comment by bacongobbler** [comment]
Homebrew by default will install all of the dependencies by default, but users can run with `brew install draft --ignore-dependencies` if they have them already installed on their system.

> Are we thinking we might detect the existing environment, and THEN make decisions? Whatchya thinking?

Unfortunately homebrew doesn't do the existing environment detection unless the dependencies were installed with homebrew previously. The user has to be well-informed about their own environment and make that decision themselves.

**Comment by squillace** [comment]
so, we should focus on the output being very clear to this effect, I should think. Brew often prompts me to run some command in order to wire up what it installed to use what I already have.
