### ISSUE TITLE
canary builds failing in master

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#252]
Every time we upload the canary binaries to Azure, it's failing with the following:

```
+ az storage blob upload-batch --source _dist/ --destination draft --pattern *.tar.gz*
ERROR: 
HTTPSConnectionPool
```

Perhaps we just need to bump the az CLI version in deis/jenkins-node?

**Comment by bacongobbler** [comment]
dropped an issue at azure-cli to see if they know any good debugging tips: https://github.com/Azure/azure-cli/issues/4223

**Comment by mboersma** [comment]
Yep, that looks like the same issue. Hopefully deis/jenkins-node#21 fixed it for draft too.

**Comment by bacongobbler** [comment]
Just [waiting on a job](https://ci.deis.io/job/Azure/job/draft/job/master/125/console) I kicked off on master to see if it's been fixed by that ticket. Thank you for indirectly fixing this, @mboersma! 😀

**Comment by bacongobbler** [comment]
Yep, this fixed the issue.
