### ISSUE TITLE
implement `draft logs`

### ISSUE THREAD

**Issue by fibonacci1729** [Azure/draft#273]
Per each draft up, draftd will generate a contextually unique build id to correlate the aggregated verbose logs to the invocation. `draft logs [options] <build_id>` will enable users to retrieve these logs out of band.

To accomplish this:
* draftd will need to emphemerally cache a compressed archived aggregation of the logs generated by draft up.
* draftd should support a bi-directional stream for paginating the logs.
* draftd should accept and handle requests to download the archive in its entirety.
* draftd should accept and handle options to configure the seek point and page size.
* draftd should accept and handle filters to enable, for instance, "given build id 'X', i want the logs for the image build stage only".

**Comment by bacongobbler** [comment]
Another thought I had about the log archives:

- I'm coming with the assumption that users are not concerned about server-side log persistence, so draftd should have some form of log rotation occurring within a reasonable time frame (48 hours by default?)

**Comment by bacongobbler** [comment]
@michelleN would you like to tackle this? I started a little with #283 but fell flat. Would the UX of `draft connect` (connecting to every build pod's logs) be a great example on how we could tackle this?

**Comment by michelleN** [comment]
_summarizing conversation on draft logs experience here_

Going with tailing or dumping the last _n_ number of lines of the draftd pod logs for implementing an MVP of draft logs. This will help the user understand why a build failed without having to drop down into kubectl and make for a good draft UX in the happy as well as not so happy paths.
