### ISSUE TITLE
Draft Init: Incompatible Versions Client Error

### ISSUE THREAD

**Issue by dbettin** [Azure/draft#274]
I am receiving the following error when running `draft init` (v0.6 and defaults) on Fedora 25:

`Error: error installing Draft: rpc error: code = Unknown desc = incompatible versions client: v2.5+unreleased server: v2.3.1`

**Comment by bacongobbler** [comment]
Did you make sure to follow the release note instructions when upgrading? You need to delete the existing draft installation via `helm delete --purge draft` before calling `draft init` again.

**Comment by bacongobbler** [comment]
Oh wait... this is the helm release version. Make sure you've deployed the latest version of tiller (v2.6.0).

**Comment by dbettin** [comment]
Tiller was on an older version. Upgraded and it works.
