### ISSUE TITLE
Message Length Exceeding Max Size Error 

### ISSUE THREAD

**Issue by dbettin** [Azure/draft#275]
When running `draft up` (v 0.6) on a node project I receive the following error:

`Error: there was an error running 'draft up': error running draft up: rpc error handling up_build recv: rpc error: code = Internal desc = grpc: received message length 6075474 exceeding the max size 4194304`

**Comment by bacongobbler** [comment]
this has been fixed in #276. Thanks for the report!

**Comment by dbettin** [comment]
Thanks! Should I start running draft from master?

**Comment by bacongobbler** [comment]
Yes, if you want to test this fix you should be running from master. As of right now the canary builds are failing due to #252 but feel free to build from source following the documentation.
