### ISSUE TITLE
Unable to push/pull from AWS ECR Container Registry

### ISSUE THREAD

**Issue by eugeneware** [Azure/draft#285]
Draft currently has a few assumptions that mean that it won't work if you're using a private registry with AWS ECR.

The first is that there's an assumption of a an `org` prefix. So you end up with a final repo URL of `12345.dkr.ecr.us-east-1.amazonaws.com/orgname/imagename:tag`.

Due to ECRs bizarre set up, you don't usually have a repo prefix. But generally just a `12345.dkr.ecr.us-east-1.amazonaws.com/imagename:tag`

Also, the image repo actually has to exist before using it. So if you push into a repo image URL that doesn't exist, it *doesn't* create it by default (would be nice if it did).

And, finally, the username / password combination in AWS expires after 12 hours and needs to be refreshed.

docker pulls from an AWS instance node *generally* have IAM roles that allow you to pull from them, and there is a default system service which will refresh the tokens every 12 hours.

I'm not 100% sure how draft works, whether we could use these default permissions to make image pulling work out of the box.

Also, currently, `draft init` asks for username/password, but if you get the password details using `aws ecr get-login --no-include-email` you end up with a huge password token that won't actually paste into the cli.

I know it's super early days on draft, and it's a very exciting project, but I know a lot of the AWS crowd uses private registries, so without it - it's a non-starter.

Is there a workaround?

I considered editing `draftd` runtime parameters, and the secrets files. But without the 12 hour token refresh thing I'm not sure it would help much.

Keep up the amazing work!

**Comment by eugeneware** [comment]
OK. So I worked out how to hack it into submission (at least for 12 hours).

You need to edit the `args` on the `draftd` deployment to change the `--registryAuth=XXX` field from the `XXX` to be the result of running the following command:

``` bash
aws ecr get-login --no-include-email | awk '{ print "{\"username\":\"AWS\",\"password\":\""$6"\"}" }' | base64
```
Unfortunately you'll need do this every 12 hours. So would be awesome to have the token refresh supported natively in draft.

NB: Regarding the `org` issue mentioned above, you will need to create the repository with something like:

``` bash
aws ecr create-repository --repository-name=YOURORG/APPNAME
```
before you can push to the repo.

**Comment by bacongobbler** [comment]
> The first is that there's an assumption of a an org prefix. So you end up with a final repo URL of 12345.dkr.ecr.us-east-1.amazonaws.com/orgname/imagename:tag.
> 
> Due to ECRs bizarre set up, you don't usually have a repo prefix. But generally just a 12345.dkr.ecr.us-east-1.amazonaws.com/imagename:tag

This is also an issue for Azure Container Registry as well. We are fixing that in #281.

> Also, the image repo actually has to exist before using it. So if you push into a repo image URL that doesn't exist, it doesn't create it by default (would be nice if it did).

Yes, it certainly would be nice. This is inconsistent with behaviour from all the other container registries out there, so I'm hesitant about making a fix for this within Draft. Every other container registry (dockerhub, ACR, quay, etc) all create repositories on-the-fly when you push, and a "registry create" endpoint does not exist natively for the [Docker Registry API Spec](https://docs.docker.com/registry/spec/api/).

As far as token refreshing is concerned, I've seen many users deploy [sidecar containers like this one](https://blog.spinnaker.io/using-aws-ecr-with-spinnaker-and-kubernetes-2b2a9bac8bd1) beside the container to cycle auth tokens. Perhaps you can hack up draft to do the same for now and see what comes from it. Again this is a cloud provider specific issue which we aren't concerning ourselves with at the moment, but please feel free to explore this area some more and provide feedback :)

Right now our focus is entirely on very basic minikube support w/ the in-cluster registry add-on as the base case. We're not focusing on cloud provider support at the present time. If they work with Draft that's great, but it's not going to be a core focus until we can nail down the user experience first for v0.7.0 (and possibly bleed into v0.8.0).

That being said, if you want to hack on cloud provider support, I don't see any issue with that and you're more than welcome to submit PRs!

**Comment by eugeneware** [comment]
Thanks @bacongobbler for the response.

I agree, focusing on the development experience should be the main priority.

I don't think in general that draft should create the repository on demand. It's not a big deal to create it from the command line before-hand. But it is surprising behaviour that adds friction to the developer experience. Maybe it could be an option that could be enabled.

One barrier to getting the sidecar method to work is that the secrets are baked into the command line arguments at the moment, so any sidecar would have to modify the running command line arguments of draftd and then update the deployment. We'd have to update draft to read the secrets from a file.

So perhaps that would be the first step? Adding on a sidecar after that would be pretty straightforward.

**Comment by errordeveloper** [comment]
This looks related to #355, for which I have a work-in-progress PR right now #364.
