### ISSUE TITLE
Java draft packs should be called java-maven and java-gradle

### ISSUE THREAD

**Issue by selvasingh** [Azure/draft#288]
Reference https://github.com/Azure/draft/tree/master/packs

**Comment by bacongobbler** [comment]
Because of how the liguist -> pack translation works this won't be as easy as `git mv`. Linguist detects Maven apps as "Maven POM", hence the pack name.

Any particular reason other than for vanity cases?

**Comment by squillace** [comment]
OK, but will people be looking for maven pom apps in search, or Java maven, or... what do we think? Do we think linguist always uses the right human words?

**Comment by bacongobbler** [comment]
I'm partial to keeping all gradle apps detected by Draft as shown as

> --> Draft detected the primary language as Gradle with 90.157480% certainty.

Rather than

> --> Draft detected the primary language as java-gradle with 90.157480% certainty.

However, I have introduced language aliases in #290 which should solve the "Maven POM" language pack naming issue.

**Comment by squillace** [comment]
@selvasingh, what do you think you would like to see, given that we're using a language detection tool that ejects specific names already? I think it's weird that the `language` is detected as gradle, which is not a language, really. Not a high pri issue, but something for us to think about.
