### ISSUE TITLE
Increase max message size

### ISSUE THREAD

**Issue by aronasorman** [Azure/draft#289]
Hi there,

I'm trying to integrate draft as part of our CI toolchain. One thing that I'm trying to do now is uploading our source code. In our case, we vendor the libraries that we use, to allow us to avoid fetching dependencies during runtime.

However, that means that our total message size is bigger than the maximum of 4MB. Specifically, I get this error:

```
Error: there was an error running 'draft up': error running draft up: rpc error handling up_build recv: rpc error: code = Internal desc = grpc: received message length 20744023 exceeding the max size 4194304
```

I see that the server's max message size is hardcoded in a constant in `pkg/rpc/server.go`. For now we're using a fork that increases this to 40MB, It would be nice to have this default increased in the main repo, or even configurable at runtime (or through the config file).

**Comment by bacongobbler** [comment]
We bumped the max message size in #276 but we haven't cut a release with that fix yet. Thanks for the report!

**Comment by chekkan** [comment]
Make sure that the `.dockerignore` file contains `node_modules` entry.
