### ISSUE TITLE
draft up UI should clearly show success or failure in text

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#294]
The emojis are adorable and should stay but may not be supported in all shells, so we should also state success or failure next to the stages that are outputted during `$ draft up`

**Comment by bacongobbler** [comment]
Ahh! So instead of "⚓️" it should be "SUCCESS ⚓️", and same with "❌", which should be "FAIL ❌". Does this sound good?

**Comment by bacongobbler** [comment]
Alternatively, we could show "SUCCESS" by default and hide the emojis behind a `--emoji` feature flag similar to `yarn install --emoji`. Either way works for me.

**Comment by bacongobbler** [comment]
...Or ship two versions of draft: draft-boring and draft. You can guess which one has emojis ;)

(kidding)

**Comment by michelleN** [comment]
haha yeah I like the fist idea with having the test next to the emojis. 
We'd probably want to ask Brian how he feels about the `--emoji` flag when he comes back and what he thinks the default behavior should be. I personally think the emojis are cute and just want the text alongside for clarity like you mentioned. I'd also be inclined to add a `--disable-emoji` flag in case people who don't have emoji functionality get annoyed of the white boxes that pop up instead.

**Comment by michelleN** [comment]
closed this issue since we added the success and fail text. opened another issue (#304) for emoji flag discussion
