### ISSUE TITLE
draft connect should create a tunnel to all containers in a pod

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#299]
Currently, draft connects to the first container port of the first container in a pod. A user may very well want to connect to multiple containers in a pod, so we should support that. For example, this would help debug sidecar container behavior in a pod.

**Comment by isutton** [comment]
Maybe using labels/annotations along the lines of the following: https://github.com/schubergphilis/kube-compose.

**Comment by radu-matei** [comment]
I think this can be safely closed.
