### ISSUE TITLE
java pack Dockerfile error

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#302]
Seeing this error in draftd while building image
```
Step 1 : FROM maven:3.5-jdk-8-alpine as BUILD
buildApp: buildImg error: Error parsing reference: "maven:3.5-jdk-8-alpine as BUILD" is not a valid repository/tag
```

**Comment by bacongobbler** [comment]
Are you running draftd locally, and if so what version of Docker are you running? IIRC the multi-container build steps is a relatively new feature in Docker so you'll need [17.05.0-ce](https://github.com/Azure/draft/blob/master/chart/draftd/templates/deployment.yaml#L44) at the very least.

**Comment by bacongobbler** [comment]
gentle ping; are you still seeing this when hacking or has this been fixed by updating docker? :)

**Comment by bacongobbler** [comment]
closing as old/inactive :)
