### ISSUE TITLE
ASP.NET Core 2

### ISSUE THREAD

**Issue by nikolay** [Azure/draft#325]
It's been out for a while. You, as Microsoft, should have a starter pack for it out of the box.

**Comment by squillace** [comment]
Hey! Why don't you contribute, since we're so lame. :-) In fact, you're right. Let's get someone on that.

**Comment by bacongobbler** [comment]
Nobody on the team has .NET Core experience, believe it or not. Having a beefier set of language packs available is on the roadmap, but we're still nailing down the user experience before we start expanding beyond our own knowledge base.

As @squillace said, write one up if you feel motivated!

**Comment by nikolay** [comment]
@squillace The last time I touched .NET was back in 2008, but I will give it a try and submit a PR as it doesn't look a big deal anyway.

**Comment by squillace** [comment]
@nikolay: I'll make you a deal. You give it a shot (hopefully it should be fairly straightforward), and I'll have the core team come over and vet it. :-) Everyone will learn something, I'm sure.

**Comment by nikolay** [comment]
@squillace You made me an offer I can't refuse! 😄

**Comment by squillace** [comment]
Most excellent.

**Comment by squillace** [comment]
Yeah, @nikolay, I think we can get some help. https://twitter.com/sajaya/status/908180245026529282. :-)

**Comment by bacongobbler** [comment]
One problem with adding "another" ASP.NET pack at this point is that Draft does not have a way to determine the difference between two identical packs: #308 

We first need to handle the case where there may be multiple versions of a pack available in `$(draft home)/packs` via `draft create` before we can support ASP.NET 1 and ASP.NET 2 applications identically.

**Comment by squillace** [comment]
worthwhile test case to use to solve the issue.
