### ISSUE TITLE
draft connect should wait for pods to come up before establishing connection

### ISSUE THREAD

**Issue by squillace** [Azure/draft#329]
for all apps, the UX for the current `draft up` to `draft connect` has a gap: the starting of the containers. It doesn't take that long on minikube, end even shorter in the cloud with bigger machines, but I'm wondering whether it's not a better experience to check the pods for completion as part of the Building, Pushing, Releasing.... stages. Truth is, "Releasing" is really, "deploying the chart" and as a result, it returns SUCCESS when your chart is deployed but the containers are unready. This means that you are lead to _expect_ that you can immediately `draft connect`, but that fails for short while until the pods are running. 

Below, after Releasing comes back as success, on my minikube there's about ten seconds to wait before you can use `draft connect`. 

![image](https://user-images.githubusercontent.com/1422718/30410970-170a4b4e-98c3-11e7-8a98-4e68c4853aef.png)

**Comment by bacongobbler** [comment]
In draft.toml you can set `wait` to true to make draft wait until the pods have deployed and are running. This is disabled by default due to issues with helm when the app fails to come up, but it would be great for demos to flip this flag.

related: https://github.com/Azure/draft/issues/200

**Comment by bacongobbler** [comment]
The [Draft User Guide](https://github.com/Azure/draft/blob/master/docs/user-guide.md) goes into a little more detail on what can be tuned in draft.toml.

**Comment by bacongobbler** [comment]
re-titled the issue to better reflect the work required here to fix this.

cc @michelleN

**Comment by radu-matei** [comment]
Don't have experience with the Helm `--wait` flag, but can't we simply wait for the pods to be running by using the Kubernetes client directly?

Something in the lines [here](https://github.com/radu-matei/kube-exec/blob/master/kube_util.go#L183)

**Comment by radu-matei** [comment]
How about this? 😄 
Would using the Kubernetes API to wait for pods make sense?
