### ISSUE TITLE
--ingress-enabled is silently ignored

### ISSUE THREAD

**Issue by kingdonb** [Azure/draft#336]
When I do `draft init --ingress-enabled` the option appears to be silently ignored and I am never prompted for the basedomain setting.  I can edit the draftd deploy and change the setting there, from:

```
- args:
  - start
  - --registry-url=$(REGISTRY_SERVICE_HOST)
  - --registry-auth=e30K
  - --basedomain=example.com
  - --ingress-enabled=false
```

to this:

```
- args:
  - start
  - --registry-url=$(REGISTRY_SERVICE_HOST)
  - --registry-auth=e30K
  - --basedomain=k8s.local
  - --ingress-enabled=true
```

and my next `draft up` will happily spring to life with an ingress rule that works fine on my minikube draft deployment, this was not easy to determine though and seems to be a bug.

According to `ingress.md` the `--ingress-enabled` flag should still be supported.

**Comment by bacongobbler** [comment]
From internal testing this appears to be true.

```
$ draft version -c
Client: &version.Version{SemVer:"v0.7.0", GitCommit:"0054537f5fe2561f8dc0fe3cca0fc5970f62562d", GitTreeState:"clean"}
$ draft init --auto-accept --ingress-enabled=true
...
Draft has been installed into your Kubernetes Cluster.
Happy Sailing!
$ kk get deploy draftd -o yaml | grep ingress
        - --ingress-enabled=false
```

This appears to only be an issue on minikube due to the "smart" detection logic. For ACS this works fine.

**Comment by alexpilotti** [comment]
As a workaround, here's how I "fixed it" for the time being, in case somebody else needs to automate it:

```
kubectl patch deployment/draftd --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/args/4", "value": "--ingress-enabled=true"}]' --namespace=kube
-system

kubectl patch deployment/draftd --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/args/3", "value": "--basedomain=10.0.0.100.nip.io"}]' --names
pace=kube-system
```

**Comment by bacongobbler** [comment]
This appears to have been fixed in master.

```
><> ./bin/draft init --ingress-enabled --auto-accept
><> kk get po draftd-d5686b9f4-z29cd -o yaml | grep ingress
    - --ingress-enabled=true
```

Closing this, but please re-open if this hasn't been fixed. Thanks!
