### ISSUE TITLE
Draft up isn't upping 

### ISSUE THREAD

**Issue by kris-nova** [Azure/draft#343]
So I just checked out the latest version of draft 

```
kris-nova:terraformctl kris$ draft version
Client: &version.Version{SemVer:"v0.7.0", GitCommit:"0054537f5fe2561f8dc0fe3cca0fc5970f62562d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v0.7.0", GitCommit:"0054537f5fe2561f8dc0fe3cca0fc5970f62562d", GitTreeState:"clean"}
```

and whenever I run a `draft up` I am not getting a build ID and no pods are showing in my cluster.

```
kris-nova:terraformctl kris$ draft up --debug
DEBU[0000] Created tunnel using local port: '60626'
DEBU[0000] SERVER: "localhost:60626"
DEBU[0001] INCLUDES: [.]
DEBU[0001] EXCLUDES: [/go/src/github.com/kris-nova/terraformctl/chart]


Draft Up Started: 'kindled-rodent'
kindled-rodent: Build ID:
```

also I tried to `helm install` the chart that draft created just for good measure and am getting this error:

```
kris-nova:terraformctl kris$ helm install chart/go
Error: render error in "go/templates/ingress.yaml": template: go/templates/ingress.yaml:1:14: executing "go/templates/ingress.yaml" at <.Values.ingress.enab...>: can't evaluate field enabled in type interface {}
```

Any ideas?

**Comment by squillace** [comment]
That's interesting. I just demo'd on my ubuntu machine with the same version; worked on ACS and on miniube, but I did NOT use the `--debug` switch...

**Comment by kris-nova** [comment]
I am looking at it now.. I think the problem was that I had the wrong docker registry credentials but didn't get an error saying so.. I will report back once I find out for sure

**Comment by squillace** [comment]
After chatting with Kris a bit, she installed it without torching either ~/.draft first or her repo, which means she likely had artifacts floating around that made it impossible to run. We'll look into it tomorrow, and if true, it means we need to have a a) doc for upgrading and b) possibly the draft init plug in might validate something, dunno.

**Comment by bacongobbler** [comment]
We used to error out with a message like "$DRAFT_HOME not found. Did you make sure to run `draft init --client-only`?" so this sounds like a regression.

**Comment by bacongobbler** [comment]
As far as upgrade concerns are, we do document the upgrade workflow [every release](https://github.com/Azure/draft/releases/tag/v0.7.0):

> Keeping in tradition with previous releases, Draft currently does not have a way to upgrade the server-side portion. In order to upgrade, you will need to delete Draft from your cluster with helm delete --purge draft, delete your local Draft configuration via rm -rf $HOME/.draft, grab and unpack one of the clients provided and re-run draft init according to the installation guide.

And for users installing draft via homebrew, we [automatically perform this step for them](https://github.com/Azure/homebrew-draft/blob/74fd2a1d718d1fad17b8bbcdda567bded8830c41/Formula/draft.rb#L17), so this shouldn't be an issue only for users installing from source.

In any case, fixing that regression should help resolve this bug so users have directions on how to move forward.

**Comment by squillace** [comment]
Kris was busy at whatchamacallitcon, so I'll follow up with her and figure it out.

**Comment by radu-matei** [comment]
I also had at some point wrong credentials for the registry and I had to guess that was the problem...
