### ISSUE TITLE
animation background with white terminal background

### ISSUE THREAD

**Issue by errordeveloper** [Azure/draft#350]
I like colourful UI, but it currently doesn't look particularly great on my terminal.

<img width="1738" alt="screenshot 2017-09-21 15 16 49" src="https://user-images.githubusercontent.com/251467/30700639-0e185d32-9ee0-11e7-9cc1-9bc00643da28.png">

Ideally, I'd like it to either match background colour of the terminal, or just not have the black background behind some of the text.

**Comment by fibonacci1729** [comment]
Thanks for filing! Currently WIP on this (see #303).

**Comment by bacongobbler** [comment]
closing in favour of #303 so we can track discussion/progress in one ticket. Thanks!

**Comment by errordeveloper** [comment]
Thanks!
