### ISSUE TITLE
[META] error: invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#356]
There are several causes of this error:

```
time="2017-09-22T16:50:56.763305114Z" level=error msg="Handler for POST /v1.29/build returned error: invalid reference format: repository name must be lowercase"
```

One of them would be #209.

This also pops up when the registry add-on has not been enabled for minikube, which should hopefully be resolved with #213 or #306.

**Comment by bacongobbler** [comment]
Another edge case: this occurs when draft is installed in a different namespace than kube-system on minikube. This is because the registry add-on is installed into the kube-system namespace so $REGISTRY_SERVICE_HOST is unavailable in other namespaces.

**Comment by squillace** [comment]
new one for you with Draft .10.1:

```
(⎈ |aks-neu:default)draft up
Draft Up Started: 'GiraffeSample'
GiraffeSample: Building Docker Image: FAIL ❌  (1.0036s)
GiraffeSample: Build ID: 01C5Q1ZPEPRT0XTW3CWPC12FSK
(⎈ |aks-neu:default)draft logs
Starting a log stream from the draft server...
time="2018-02-07T02:37:16Z" level=info msg="server is now listening at 0.0.0.0:44135 (tls=false)"
buildApp: buildImg error: Error response from daemon: invalid reference format: repository name must be lowercase

```

Note the name of the app: "GiraffeSample". If I modify that....

```
(⎈ |aks-neu:default)draft up
Draft Up Started: 'foo-moose'
foo-moose: Building Docker Image: SUCCESS ⚓  (242.3426s)
foo-moose: Pushing Docker Image: SUCCESS ⚓  (37.2482s)
foo-moose: Releasing Application: SUCCESS ⚓  (1.8074s)
foo-moose: Build ID: 01C5Q6FF9YH76ZJGY963TG0X8P
```

**Comment by cameron-martin** [comment]
I'm getting this error too. The application name is all lowercase, draft is in the `kube-system` namespace, and minikube has the registry addon enabled.

How can I get more information on what is causing this problem?

**Comment by cameron-martin** [comment]
Restarting minikube seemed to fix my issue.
