### ISSUE TITLE
Minikube: MacOs, Registry and Tiller

### ISSUE THREAD

**Issue by wahmedswl** [Azure/draft#361]
Hi, unable to run draft on MacOs with MiniKube. Followed the installation guide at https://github.com/Azure/draft/blob/master/docs/install.md and on checking the kubernetes dashboard, following been shown in pods

```
registry-xbs18
kube-system
minikube
Waiting: ErrImagePull
0
3 minutes
subject
 
more_vert
Failed to pull image "registry:2.6.1": rpc error: code = 2 desc = Error while pulling image: Get https://index.docker.io/v1/repositories/library/registry/images: dial tcp: lookup index.docker.io on 192.168.64.1:53: read udp 192.168.64.3:43036->192.168.64.1:53: read: connection refused
Error syncing pod
error
tiller-deploy-1651615695-3r662
kube-system
minikube
Waiting: ErrImagePull
0
3 minutes
subject
 
more_vert
Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.6.1": rpc error: code = 2 desc = Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 192.168.64.1:53: read udp 192.168.64.3:49914-\u003e192.168.64.1:53: read: connection refused"}
Error syncing pod
```

tried pulling up gcr.io/kubernetes-helm/tiller:v2.6.1 manually with ```docker pull gcr.io/kubernetes-helm/tiller:v2.6.1``` and able to pull image

any help would be appreciated, thanks

**Comment by bacongobbler** [comment]
It looks like your minikube cluster does not have an internet connection and cannot pull images from https://hub.docker.com. Can you check and verify that?

```
$ DRAFTD_POD=$(kubectl -n kube-system get pods | grep draftd | awk '{print $1}')
$ kubectl -n kube-system exec -it $DRAFTD_POD -c dind docker pull registry:2.6.1
```

**Comment by wahmedswl** [comment]
@bacongobbler thanks for your quick response, checked and minikube don't have internet connectivity

**Comment by wahmedswl** [comment]
@bacongobbler able to resolve issue, ```sudo vi /etc/resolv.conf``` and added ```nameserver 8.8.8.8``` as 1st dns server

**Comment by wahmedswl** [comment]
Hi, updating ```/etc/resolv.conf``` don't fix the issue as xhyve driver seems to use ```192.168.64.1``` as dns server. Seems like xhyve drive with minikube not a good idea so switched to virtualbox. Please see https://github.com/kubernetes/minikube/issues/1442#issuecomment-322513344

Thanks for your support
