### ISSUE TITLE
change internalPort value in default packs to 3000

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#369]
Been running to plenty of example apps online which serve off of port 3000 and not 8080. 8080 is the default internalPort value. Was there a reason we picked 8080 specifically? If not, should we change it to 3000. I understand 8080 is a totally valid port but 3000 might conver the 80% use case. That's all just based off anecdata so would love some thoughts here.

**Comment by bacongobbler** [comment]
All for it.

**Comment by ultimateboy** [comment]
8080 was not arbitrary decision. Ports 8080, 8001, and 591 are assigned as "http alternate" ports via IANA: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http-alt

It does appear that port 3000 is the default for the Ruby on Rails development environment. I'd suggest just changing the ruby pack.
