### ISSUE TITLE
Support pre- and post- draft up hooks for handling tasks

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#370]
For example, I may want to script something like creating a mysql if one doesn't exist with `helm install stable/mysql -n mysql-database` because my application depends on mysql and then create a table (or tables) that my application uses.

**Comment by bacongobbler** [comment]
How do we want to architect this? Do we want to have a client-side `.draft/hooks/pre-up` and `.draft/hooks/post-up` script that is executed before calling `draft up`? I can see the value in having client-side hooks.

Perhaps we should first implement #264 and *then* tackle this. It's starting to make a lot more sense to have a dedicated config directory for all things Draft (draft.toml, draftignore, chart/, Dockerfile etc).

**Comment by michelleN** [comment]
Yeah, I like the .draft/hooks route.

**Comment by michelleN** [comment]
A draft pack author could have a draft pack where hooks live under `pack_name/hooks/pre-up` for example which can then be copied over under `.draft/ ` like @bacongobbler suggested.

**Comment by bacongobbler** [comment]
Hey! Is there anything left here we need to do in time for 0.14 or is this good to close now with #642 in master?

**Comment by michelleN** [comment]
thanks yea we can close this. We've implemented `pre-up`, `post-deploy`, and `cleanup/post-delete` tasks. Will open up a new issue for the other possible tasks. 🎉
