### ISSUE TITLE
switch to dep

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#380]
As per [the latest release of glide](https://github.com/Masterminds/glide/releases/tag/v0.13.0), it would seem that it'd make sense to migrate over to [dep](https://github.com/golang/dep) as that is starting to be absorbed into the core Go toolchain [according to their roadmap](https://github.com/golang/dep/wiki/Roadmap).

**Comment by mattfarina** [comment]
@bacongobbler It's worth noting that this is not a sure thing to make it into the go toolchain. dep, and any modern dependency manager, is a large codebase. The core go team pays attention to how much code they need to maintain. What is important is the manifest files, a sane solver, and the other details. dep is the next iteration.
