### ISSUE TITLE
Request: draft init --minikube to force minikube detection

### ISSUE THREAD

**Issue by kingdonb** [Azure/draft#384]
This is a minor feature request

I would like a `draft init --minikube` option, I am using Draft on Minikube and I have overriden the kube-context to work with some VirtualBox NAT rules on my VPN.

My workflow currently looks like this:

```shell
# (There is a block of entries like this in my .kube/config:
# - cluster:
#    certificate-authority: /Users/kingdonb/.minikube/ca.crt
#    server: https://kubernetes.default:8443
#  name: minikube-vpn
# contexts:
# - context:
#    cluster: minikube-vpn
#    user: minikube
#  name: vpn
# )
#
minikube start
helm init
draft init
# (connect to the VPN)
kubectl config use-context vpn
kubectl --namespace=kube-system get po -w
```

This works great!

But if I start the process of installing draft and I am already connected to the VPN, minikube detection fails, I am prompted to enter a registry, and the way to resolve it for me is to disconnect from the VPN, `use-context minikube`, and only draft init while I'm disconnected from the VPN.

**Comment by bacongobbler** [comment]
This should be solved via #168. Under #168 the user will have to specify the cloud provider on `draft init` e.g. `draft init --driver minikube`

**Comment by kingdonb** [comment]
Awesome! Thank you

**Comment by bacongobbler** [comment]
closing in favour of #168
