### ISSUE TITLE
Allow way to turn off progress meter

### ISSUE THREAD

**Issue by technosophos** [Azure/draft#386]
It would be nice to have a flag that disabled the progress meter during `draft up`. This is because in some non-interactive presentations of STDOUT, they ignore the backspace character, which means I get a bazillion lines of output.

Maybe just `draft up --quiet`, which would just display errors, and nothing else?

**Comment by bacongobbler** [comment]
We've talked about selectively disabling features such as emoji support and colorized output, so I don't see why not!

**Comment by sj14** [comment]
I would like to work on this small enhancement during Hacktoberfest.

**Comment by bacongobbler** [comment]
Go for it! :)
