### ISSUE TITLE
draft connect flag for specifying which container to connect to

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#399]
Currently, draft creates a connection to the first container in a pod. #299 suggests that we create a connection to all containers in a pod. A user may also want to specify which container they want to connect to. Should we add a flag for that?

**Comment by isutton** [comment]
Please. Our use case will include applications with side-cars, so this would be really helpful.

Perhaps adding some sort of label/annotation to the "default" container, and an option to connect to other containers on the same pod.

`draft connect` would then either connect to:

* The only container in the pod, in the case there's only one;
* The first container in the pod (perhaps listed alphabetically?) in the case of many containers;
* The "default" container of the pod if there's a label/annotation in  the container;
* The specified container through `draft connect -c my-container`

**Comment by michelleN** [comment]
Would it be helpful if the default scenario was creating a connection for all containers? 

I really like the idea of adding a `-c` flag for which container to connect to. It is explicit and the developer wouldn't necessarily have to go mess with the kubernetes manifests in the chart.

The only issue I have with relying on labels or annotations is that I want to burden the developer with knowing too much about which part of the Kubernetes manifest to change. What do you think?

**Comment by isutton** [comment]
Sorry for the delay, completely missed this.

I understand your issue, but I think I haven't explained well enough that point. It was meant to aid the Chart developer to indicate which container to connect to by default and would be only specified if the setup would be rather complex. 

Although I think that this could be a "nice to have" and would depend on actual real life scenarios, thus it wouldn't be the first thing I'd implement.

**Comment by radu-matei** [comment]
@michelleN - is the `-c` flag something you want to add?
I might take a look at it during the weekend :)

**Comment by michelleN** [comment]
oh yeah that would be great! feel free to ping me if you have any questions. I'm @mnoorali on the kubernetes slack.

**Comment by michelleN** [comment]
@isutton yeah I'm with you on idea of adding this notion of a default container to connect to. I think using labels or annotations would be a great way to go about that.

Another option is to connect to all of the containers in the pod and provide a localhost url for each container. Do you think if that were the case, you'd still want to see default logic for connecting to one container? Not saying it has to be one or other; I just want to get your take.

**Comment by radu-matei** [comment]
Added in #528
