### ISSUE TITLE
[meta] fix windows support

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#406]
This ticket is to track what needs to be done to add Windows support to Draft.

We build binaries for Windows, but at this time `draft init --client-only` fails on Windows due to #396. This appears to be the only blocker.

**Comment by alexpilotti** [comment]
draft init requires also a shell and tar from what I can see, which is definitely a no-go on Windows :-)

.\draft.exe init
Adding plugin https://github.com/Azure/draft-pack-repo...
C:\Users\Administrator\.draft\plugins\draft-pack-repo/scripts/get.sh: line 28: draft: command not found
Downloading https://github.com/Azure/draft-pack-repo/releases/download/v0.2.0/pack-repo-v0.2.0-windows-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0    873      0 --:--:-- --:--:-- --:--:--   937
100 2945k  100 2945k    0     0   539k      0  0:00:05  0:00:05 --:--:--  698k
C:\Users\Administrator\.draft\plugins\draft-pack-repo/scripts/get.sh: line 105: tar: command not found
Failed to install draft-pack-repo
\tFor support, go to https://github.com/Azure/draft-pack-repo.
Error: plugin install hook for "pack-repo" exited with error
Error: plugin install hook for "pack-repo" exited with error

**Comment by bacongobbler** [comment]
Yep! That's what is being tracked in #396. :)

**Comment by bacongobbler** [comment]
This should now be fixed as of #396. If you're working on a dev branch, please make sure to rebase from master before re-running `draft init` as this is a backwards incompatible change.

Now all we need to do is make sure we add back the links to the Windows binaries in the docs :)

**Comment by bacongobbler** [comment]
minor blocker: #682 

Once we release draft-pack-repo 0.4.0, *then* we should be ready to open the floodgates.
