### ISSUE TITLE
draft create does not copy the .dockerignore file

### ISSUE THREAD

**Issue by jumal** [Azure/draft#427]
When doing for example a "draft create -p java" the .dockerignore file present in the Java starter pack is not copied to the project

**Comment by michelleN** [comment]
Hey @jumal - Thanks for pointing this out. It looks like we're only copying the `charts/` dir and the `Dockerfile`. We should either add .dockerignore to the list of files we copy OR we can choose to copy anything in the pack over to the application directory. 
Would be interested in what you think.


Also, thoughts? @bacongobbler @fibonacci1729 
I'd opt for copying everything over. That'll make it easier to support scripts/hooks later on.

**Comment by jumal** [comment]
Hi Michelle. Thanks for your quick reply. I would personally favour the approach copying everything. I currently have directories in my custom starter packs that currently need to be copied using scripting. Having Draft copying everything would definitively help

**Comment by bacongobbler** [comment]
This would be a great addition.

**Comment by bacongobbler** [comment]
Something brought up in https://github.com/Azure/draft/issues/549 is the ability to copy the contents of non-chart directories in the pack as well, which would be useful to bring into #453.
