### ISSUE TITLE
There's no way of refreshing a base image once it's pulled into draftd's dind

### ISSUE THREAD

**Issue by isutton** [Azure/draft#428]
Once an image is pulled into draftd's dind, there's no way to refresh it.

In order to refresh an updated base image, I had to:

```
$ kubectl exec -it draftd-67bb886665-ntxz7 -c dind \
    docker pull docker-registry/draft/perl:onbuild
```

According to the following, the only build option passed is the resulting tag:

https://github.com/Azure/draft/blob/21cf4af77195423b5238adfdbfdd027da0de9695/pkg/draft/server.go#L147

An idea would be add to `draft up` a flag to indicate whether or not pulling the base image should be attempted by draftd.

**Comment by bacongobbler** [comment]
As of #573 this can now be done by invoking a `docker pull` before a `draft up`. Closing!
