### ISSUE TITLE
Docker-in-docker doesn't start on Ubuntu in AWS

### ISSUE THREAD

**Issue by gergnz** [Azure/draft#431]
# Symptoms
* dind container won't start with overlay filesystem error

# Environment
Rancher 1.6.10
Kubernetes 1.7.7
Ubuntu 16.04

# Fix
Set the strorage-driver to overlay:

/etc/docker/daemon.json:
```javascript
{
  "storage-driver": "overlay"
}
```

**Comment by squillace** [comment]
Hmmmm. Interesting.
