### ISSUE TITLE
example-python Application from Getting Started Docs Fails during 'draft up'

### ISSUE THREAD

**Issue by aananthraj** [Azure/draft#437]
### Action:

Tried executing example-python from the draft official documentation.

### Expected Behaviour:

As specified in docs.
```
$ draft up
Draft Up Started: 'example-python'
example-python: Building Docker Image: SUCCESS ⚓  (73.0991s)
example-python: Pushing Docker Image: SUCCESS ⚓  (69.1425s)
example-python: Releasing Application: SUCCESS ⚓  (0.6875s)
example-python: Build ID: 01BSY5R8J45QHG9D3B17PAXMGN
```

### Actual Behaviour:

Draft up fails with the following error.

```
~/draft/examples/example-python  : $ draft up
Draft Up Started: 'pilfering-lemur'
pilfering-lemur: Building Docker Image: FAIL ❌  (0.9986s)
pilfering-lemur: Build ID: 01BZXQA6YMN0R0E780R4WPX0N5
```

### Additional Info:

```
~/ : $ draft version
Client: &version.Version{SemVer:"v0.8.0", GitCommit:"6edb87f6e85d019fc3f708d31ca76270b765a9b0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v0.8.0", GitCommit:"6edb87f6e85d019fc3f708d31ca76270b765a9b0", GitTreeState:"clean"}
```

```
~/ : $ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Comment by bacongobbler** [comment]
Hey @aananthraj! Would you mind posting the output from `draft logs`? Thanks!

**Comment by aananthraj** [comment]
Thanks for the prompt response @bacongobbler.
The issue was with docker registry URL , where i accidentally added my docker username with the URL. It resulted in the following error.
```
buildApp: buildImg error: Error response from daemon: invalid reference format: repository name must be lowercase
```
The issue is resolved now . Thanks for pointing the logs feature in draft. 
will close this issue now.

**Comment by iameli** [comment]
For anyone else getting here from Google: I got that same `repository name must be lowercase` issue when I had run `draft init` on a minikube cluster for which I had not yet run `minikube addons enable registry`. I'm not sure why the nonexistent registry URL contained upper case characters, but in any event running `minikube addons enable registry` followed by another `draft init` resolved the issue.

**Comment by bacongobbler** [comment]
@iameli thanks for the report. We’re following up with that issue in #356.

**Comment by quantum-fusion** [comment]
I ran draft logs, and determined that the VPN connection was blocking incoming traffic.  I took down the firewall VPN, and then ran minikube addons enable registry followed by another draft init resolved the issue.

**Comment by radu-matei** [comment]
@quantum-fusion - did you mean to post the last comment on #776 by any chance?

**Comment by quantum-fusion** [comment]
Yes, I ran through your steps, and even after adding @iameli recommendations for minikube addons enable registry. 

See #776 for the full transcript, because it still generates an error and times out.  

% draft connect
Error: cannot get pod with buildID 01CE6JAGCZTP5F1FNJY1S2DFB6: timed out
