### ISSUE TITLE
buildApp: buildImg error: Error response from daemon: client is newer than server (client API version: 1.29, server API version: 1.24)

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#443]
This error occurs on AKS. The docker daemons are an older release.

**Comment by bacongobbler** [comment]
filed https://github.com/Azure/AKS/issues/63.

**Comment by zachgrayio** [comment]
Is there a workaround here?

**Comment by bacongobbler** [comment]
There's no workaround available here. As of https://github.com/Azure/acs-engine/issues/1874 you can deploy an ACS-Engine cluster with a newer version of Docker, though. I think we should revert #434 and tackle the problem from another angle.

**Comment by RainerAtSpirit** [comment]
Is there any update on this one? I'm encounter this with a new AKS cluster, but couldn't find any documentation how to specify the docker version on creation.

**Comment by bacongobbler** [comment]
None other than what I mentioned above. We're working on refactoring the init process via #168 so it's taking longer to implement a proper fix. For now I'd suggest testing against a minikube cluster.

**Comment by anilreddyv** [comment]
@bacongobbler having same issue with coreos based tectonic cluster too that is running 1.7.9 k8 with docker 1.12 version. Keep us posted when this will be fixed. Thank you.

Starting a log stream from the draft server...
time="2018-01-15T05:03:43Z" level=info msg="server is now listening at 0.0.0.0:44135 (tls=false)"
buildApp: buildImg error: Error response from daemon: client is newer than server (client API version: 1.29, server API version: 1.24)

**Comment by bacongobbler** [comment]
#494 fixes the problem if you want to try that out.

**Comment by zachgrayio** [comment]
I see this is closed but I'm still getting this error locally when trying to run on minikube on my Mac.

`docker version` shows the following:

```
Client:
 Version:       18.03.0-ce-rc1
 API version:   1.24 (downgraded from 1.29)
 Go version:    go1.9.4
 Git commit:    c160c73
 Built: Thu Feb 22 02:34:03 2018
 OS/Arch:       darwin/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      1.12.6
  API version:  1.24 (minimum version )
  Go version:   go1.6.4
  Git commit:   78d1802
  Built:        Wed Jan 11 00:23:16 2017
  OS/Arch:      linux/amd64
  Experimental: false
``` 

I'm not sure where exactly the conflicting client API version is coming from. Is there some other method by which we should be installing or configuring our local Docker engine here?
