### ISSUE TITLE
What's the reasoning behind choice of the "toml" file format?

### ISSUE THREAD

**Issue by trondhindenes** [Azure/draft#450]
imho toml adds yet another format to the mix - it doesn't provide any value over yaml, so why use yet another format?
Draft should default to yaml formatted files, since:
- yaml parsers can also parse json, so json support is baked in "by default"
- yaml is already used by kubernetes and docker-compose and as such can be considered the "default format" for container orchestration tasks.

EDIT: I just read the "why toml" section, kudos for adding it. I'd argue that at least the choice of format should be just that - a choice. We've spent a lot of time experimenting with linters/tests in our CI pipeline, testing out various editor plugins for language validation etc based around yaml - I'd hate for us to have to do that all over again because someone personally doesn't like yaml and/or json.

**Comment by bacongobbler** [comment]
The reasons against yaml have been explained in https://github.com/Azure/draft/issues/326, though this is the second time it’s popped up so we should document it.

**Comment by bacongobbler** [comment]
Ah yes we did document it as you mentioned in [DEP 006](https://github.com/Azure/draft/blob/master/docs/reference/dep-006.md#why-toml). I’d rather not support multiple ways to define draft configuration at this point; though it sounds like a fantastic use case for a plugin!
