### ISSUE TITLE
Snap images of draft for Ubuntu and supported Linux desktops

### ISSUE THREAD

**Issue by aberba** [Azure/draft#454]
[Snap or Snappy](https://www.ubuntu.com/desktop/snappy) is a cross desktop Linux packaging tech used by several packages to make their tools one commad installable. A snap image for Draft will save us from installing Helm, Kubectl, Minikube and Draft to get draff running.  Another (more capable) option is [Flatpak](https://flatpak.org/)

**Comment by bacongobbler** [comment]
I'm going to close this for [the same reasons why the Helm team opposed supporting snap packages](https://github.com/kubernetes/helm/pull/2616#issuecomment-327290740). We decided together as a team that we're only going to support a subset of package managers for 90% of the user base, which include tarball releases and a Homebrew formula.

That being said, if the Ubuntu team or a (team invested in using snap) want to support building one for helm/draft/minikube/kubectl, they're more than welcome to use the released binary packages stored on Azure :)
