### ISSUE TITLE
How does draft output chart ?

### ISSUE THREAD

**Issue by minghsieh-prenetics** [Azure/draft#457]
Hi,

My purpose is this:

https://stackoverflow.com/q/47934460/324275

If I follow Vadim Eisenberg advice, then I need to know how draft call helm chart in the final step, aggregate all charts, and pipe to istioctl.

Btw, Istio auto inject sidecar option doesn't work for me on k8s 1.8.5.

**Comment by bacongobbler** [comment]
Did you happen to take a look at `kubectl create -f install/kubernetes/istio-initializer.yaml`? Is that what you mean by the sidecar injection option? If so how does that fail?

Even though it's still in alpha, installing the automatic sidecar injector should be the right way to do it. That way you won't have to mess around with the helm chart just to inject the sidecar into your charts.

Does that help answer your question?

**Comment by minghsieh-prenetics** [comment]
Hi, thanks for swift response. I use k8s 1.8.5 on minikube. The argument used to launched was:

minikube start --cpus 4 --memory 8192 --kubernetes-version v1.8.5 --vm-driver virtualbox --bootstrapper kubeadm --feature-gates=CustomResourceValidation=true --extra-config=apiserver.authorization-mode=RBAC --extra-config=apiserver.admission-control="Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,GenericAdmissionWebhook,ResourceQuota,PodPreset"

It returned something like: admissionregistration.k8s.io/v1alpha1 not found InitializerConfiguration. I can't post exact error message since I am still on vacation (this message is posted on my Android with my memory).

**Comment by bacongobbler** [comment]
That would be due to the fact that Initializers are an alpha feature, so it is disabled by default. To turn it on, you need to follow the instructions in [this comment](https://github.com/kubernetes/minikube/issues/2353#issuecomment-354430497) to enable admission controllers for 1.8.5. After that, automatic sidecar injection should work.

Hopefully this answers your question! If you are having further trouble with istio, I'd suggest posting an issue at https://github.com/istio/istio as they would be more likely able to answer your question, however we're always happy to answer any questions related to Draft. Thanks! :smile:

**Comment by minghsieh-prenetics** [comment]
@bacongobbler I just tried with both istio 0.3.0 and 0.4.0 using the start cli as you suggest:

`
minikube start --memory 8192 --cpus 4 \
  --kubernetes-version v1.8.6 \
  --bootstrapper kubeadm \
  --v 7 \
  --logtostderr \
  --vm-driver=virtualbox \
  --extra-config=apiserver.admission-control="Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,GenericAdmissionWebhook,ResourceQuota,PodPreset"
`

Still have error:

`
~/istio-0.4.0$ kubectl apply -f install/kubernetes/istio-initializer.yaml
configmap "istio-inject" created
serviceaccount "istio-initializer-service-account" created
deployment "istio-initializer" created
error: error validating "install/kubernetes/istio-initializer.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"admissionregistration.k8s.io", Version:"v1alpha1", Kind:"InitializerConfiguration"}; if you choose to ignore these errors, turn validation off with --validate=false
`

**Comment by bacongobbler** [comment]
I’m sorry I can’t help you further; I’m just relaying what I found out by googling. I’d follow up with the team behind istio on how to fix this to unblock you. They’ll know more about how to get you started with istio than I would. :)

**Comment by minghsieh-prenetics** [comment]
Close this issue for now with following minikube start command:

`minikube start --memory 8192 --cpus 4  --kubernetes-version v1.8.6  --bootstrapper kubeadm  --vm-driver=virtualbox  --v 7  --logtostderr  --feature-gates=AllAlpha=true  --extra-config=apiserver.runtime-config="api/all=true,admissionregistration.k8s.io/v1alpha1=true"`
