### ISSUE TITLE
Minikube install auto sidecar error

### ISSUE THREAD

**Issue by minghsieh-prenetics** [Azure/draft#459]
Hi,

Please see:

https://github.com/Azure/draft/issues/457

I don't int

**Comment by minghsieh-prenetics** [comment]
I don't intend to duplicate previous issue, but it didn't get resolved.

**Comment by bacongobbler** [comment]
Hey, I just ran out of the office for the day so I wasn’t available to re-open it. Let’s close this one and re-open the old one.
