### ISSUE TITLE
`draft connect`

### ISSUE THREAD

**Issue by michelleN** [Azure/draft#467]
Creates a local tunnel to the application deployed on kubernetes, returning a localhost URL for debugging.

- This is a meta issue to track `draft connect`'s progress from alpha to beta. We'll finalize design and UX around draft connect here.
- There have been several feature and configuration requests for `draft connect` since its initial release
- One open question is, should the `draft connect` experience automatically be part of `draft up`. Feedback here from end users would be greatly appreciated
 
Items:
- [x] #429, #472 Tackling this issue of specifying a local port to connect to gives us the opportunity to build a way to consistently configure default connect options in the draft.toml file
- [x] #329 
- [x] #471

**Comment by i386** [comment]
@michelleN playing with Draft today and its very nice! I have some thoughts around the ergonomics of `draft connect` and `draft up` for the "edit->publish->see" cycle.

I found it a little akward that I needed to restart `draft connect` and fish out the apps tunnel URL every time I executed `draft up`. What if `draft up` established the `draft connect` tunnel initially and then subsequent `draft up` commands reused the same tunnel connection? That way you could have `draft up` hooked into something like livereload, publishing changes to kubernetes, as the developer edits their source code.

**Comment by bacongobbler** [comment]
I think that might be possible with #429. We're toying around with similar ideas though, yeah.

**Comment by michelleN** [comment]
Thanks for the feedback @i386. Your feedback on workflow is very helpful. I've updated the meta issue description (above) with features that will get us to the workflow you've described.

**Comment by radu-matei** [comment]
Added in #600

**Comment by michelleN** [comment]
All aspects of this issue have been addressed. Thanks!
