### ISSUE TITLE
draft init to allow container registry, user/pwd to be passed in as CLI arguments

### ISSUE THREAD

**Issue by jstrachan** [Azure/draft#479]
if the docker registry, user and pwd cannot be deduced (e.g. for minikube) then the user is prompted for them on the CLI. it'd be nice to allow them to be passed on the CLI as arguments as well for easier scripting.

Happy to submit a PR if folks think its a reasonable thing to do

**Comment by bacongobbler** [comment]
We are currently re-working `draft init` via #168 so I'd hold off at this time. That is good feedback though. I'll see what I can do about that. :)
