### ISSUE TITLE
Ksonnet

### ISSUE THREAD

**Issue by bhack** [Azure/draft#482]
Will there be any relationship of Draft with Ksonnet for generating Helm charts?

**Comment by michelleN** [comment]
That's a great question. It's not on the current roadmap. Are you currently using ksonnet and looking to see this kind of integration?

**Comment by bhack** [comment]
We are exploring this in this in https://github.com/tensorflow/k8s/issues/136

**Comment by bacongobbler** [comment]
Hey @bhack, would you mind elaborating a little more on what kind of integration you'd like to see? How would ksonnet and Draft work together?

**Comment by bhack** [comment]
A Draft pack has a Docker and an Helm chart. We could maintain a ksonnet json that will emit an Helm chart instead of an Helm Chart directly. So it would be useful when you need to customize the Helm and you can still use Ksonnet.

**Comment by bhack** [comment]
See also https://github.com/kubernetes/helm/issues/2577

**Comment by jbeda** [comment]
Tagging @bryanl here.  

Right now integration of ksonnet and helm is on hold until helm 3.  My understanding is that any deep integration would not be practical in helm 2.  As draft has a pretty hard dependency on helm, it makes sense to drive helm/ksonnet integration first.

Bryan?

**Comment by bacongobbler** [comment]
> My understanding is that any deep integration would not be practical in helm 2

Not entirely true... See https://github.com/kubernetes/helm/issues/2577#issuecomment-341548308.

**Comment by bacongobbler** [comment]
closing as this is ultimately Helm's decision. If Helm has an option to support ksonnet templates in Helm 3 then we'll get this functionality for free. Please follow up in upstream efforts if you want to get involved. :)
