### ISSUE TITLE
sort out the private registry auth story on `draft init`

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#49]
Right now the user story to inject registry auth details into draftd is to echo a JSON string, pipe it to base64 and use the output as the `registry.authtoken` field in the chart.

We should test out the following scenarios:

1) mimic `docker login` on `draft init` somehow, asking users for their credentials
2) fetch the auth tokens from ~/.docker/config.json, if present

That way we can "hide" this process from the end user and do it for them without any terminal hackery.

Of course, this process of attaching your own base64-encoded string as the auth token might still  be useful for those that want to do things the hard way or have their own custom setup.

**Comment by squillace** [comment]
Ignore my issue. #UserError. :-) That said, the issue is a good one.

**Comment by jackzampolin** [comment]
So I'm running into this too. How would you do it for GKE? Acording to the docs and this issue the following should (?) work:
```
draft init --set 
  registry.url=gcr.io,
  registry.org=influx-perf-testing,
  registry.authtoken=$(echo '{"username":"_json_key","password":"$(cat ~/.draft/keyfile.json)"}' | base 64),
  basedomain=communism.world --upgrade
```

**Comment by DazWilkin** [comment]
@jackzampolin I was able to get this to work on GKE using Application Default Credentials:

```
gcloud auth application-default login
gcloud auth application-default print-access-token
```

The draft init command that works for me is then:

```
ACCESS_TOKEN=$(gcloud auth application-default print-access-token)
AUTH_TOKEN=$(echo "{\"registrytoken\":\"$ACCESS_TOKEN\"}" | base64 --wrap=0)
 
draft init \
--set \
registry.url=gcr.io,\
registry.org=${PROJECT},\
registry.authtoken=${AUTH_TOKEN},\
basedomain=${DOMAIN}
```

**Comment by DazWilkin** [comment]
@jackzampolin my approach was incorrect.

I spoke with one of the Engineers working on Container Registry and here's the correction:

```
AUTH_TOKEN=$(echo "{\"username\":\"_token\",\"password\":\"$ACCESS_TOKEN\"}" | base64 --wrap=0)
```

Otherwise unchanged.

**Comment by Disturbing** [comment]
One other suggestion - After init has been called once, second time it should auto --upgrade without the flag?

If this is poor standardization, then I'd suggest disabling init and stating 'already initialized, don't forget to use --upgrade flag'.  I was in a horrible loop for 1 hour because I was forgetting the upgrade flag when I needed to update my credentials yesterday.

**Comment by bacongobbler** [comment]
I disagree that init should handle upgrades. In fact I would rather we limit the scope to *literally* initializing the cluster for the first time. After that the user can call `draft up` on draft itself to upgrade. I'd like to see that as a more solid "Turing complete" upgrade workflow.

**Comment by Disturbing** [comment]
Agreed, what's your proposal for updating credentials / basedomain / etc.  That's the key UX that needs to be solved as from what I found, the only way I could update my credentials was draft init {updated config} --upgrade.

I did not see any user stories around that on this thread, so would love to know what's the game plan there.

In short-term, would suggest updating https://github.com/Azure/draft/blob/master/docs/install.md - to share information on how to update your configuration. It would have saved me tons of time after a silly typo.

**Comment by bacongobbler** [comment]
Subsequent calls to `draft up` will update the application. You can either supply your custom registry information through [draft.toml](https://github.com/Azure/draft/blob/master/docs/user-guide.md#drafttoml) or though [values.yaml](https://github.com/Azure/draft/blob/master/chart/values.yaml). I use this during development when hacking on changes to draftd.

> In short-term, would suggest updating https://github.com/Azure/draft/blob/master/docs/install.md - to share information on how to update your configuration. It would have saved me tons of time after a silly typo.

Right now the recommended way is to use `draft init --update` as you mentioned. I intentionally avoided documenting it as that functionality is going to change sooner rather than later through a PR to close out this issue.

**Comment by bacongobbler** [comment]
part one of the plan is to improve the minikube story, starting by [contributing a registry addon to minikube](https://github.com/kubernetes/minikube/pull/1583). Once that's done, we can recommend users to use the following workflow:

```
$ minikube addons install registry
$ minikube start
$ helm init
$ draft init
```

Which at that point, draft will read the local kube config and notice that the current context name is called "minikube". It will then install draftd and point it towards the in-cluster registry.

As for Azure, we will do the same operation:

- draft will read the local kube config and notice the current context is pointing at an ACS cluster
- draft will read AZURE_RG_NAME and other envvars to search the ACS cluster's resource group for an ACR instance. If so, it will configure itself to automatically use that cluster. No authentication token will be required because ACS can talk to ACR clusters within the same resource group, as I understand it.

**Comment by bacongobbler** [comment]
My chicken-scratch writing on a whiteboard:

![img_1262](https://user-images.githubusercontent.com/1360539/27107328-59d6faae-504c-11e7-9030-edf165e41d3f.JPG)

The one problem I have right now is "how do we install an ingress controller onto ACS?" Right now there's no solid story other than `helm install stable/nginx-ingress`. I'd like this to be one less step but I think it's suitable for the moment.

**Comment by squillace** [comment]
@bacongobbler, good line on minikube, azure. Will this approach work for all registries, generally? I'll follow up with the ACR/ACS access.....

**Comment by bacongobbler** [comment]
Generally speaking, if someone were to write a Google Cloud bootstrap workflow for draft then yes. I'm limiting scope for v0.5.0 to *just* minikube and Azure for now as that happens to be the large majority of users trying out draft. All the other unrecognized providers will need to go through the manual approach we do today until someone can pick up the work for GKE, Amazon etc.

**Comment by bacongobbler** [comment]
(that someone likely being myself)

**Comment by squillace** [comment]
gotcha: just wanna make sure we have a good path for everyone. checking on acr/acs access issues now to be certain about our assumptions.

**Comment by bacongobbler** [comment]
closing in favour of #152. The discussion in that ticket more clearly demonstrates the issue and proposed solution going forward.

**Comment by bacongobbler** [comment]
> checking on acr/acs access issues now to be certain about our assumptions.

My assumptions were wrong. Either way we can still automate this process to fetch the admin username/password and pass that to draftd.
