### ISSUE TITLE
[draft create] flag to use name as chart name

### ISSUE THREAD

**Issue by rawlingsj** [Azure/draft#498]
If I have a java project called `foo` and I run 
```
draft create --pack=github.com/Azure/draft/packs/java
```
I get a folder structure created:

```
./foo
 +-  charts
       +- java
          chart.yaml # contains a chart name of `name: java`

```
It would be handy if there was a flag to set the chart name, i.e.
```
draft create --pack=github.com/Azure/draft/packs/java --name foo
```
would instead generated something like this (replacing __java__ with __foo__):
```
./foo
 +-  charts
       +- foo
          chart.yaml # contains a chart name of `name: foo`

```
There's already a `draft create --app` flag but this is related to the helm release name and not the chart name.

**Comment by fibonacci1729** [comment]
This seems reasonable at a glance. @bacongobbler, are there any hidden semantics behind using the pack-language name as the chart name that would interfere with this?

**Comment by bacongobbler** [comment]
nope. In fact I'd prefer that `draft create` bootstrapped the pack with the same name as the application. We just avoided doing that due to #292 because then the pack name would end up something like `charts/funky-monkey` which isn't at all intuitive to the user.

**Comment by jgleonard** [comment]
@rawlingsj @bacongobbler @fibonacci1729  Trying to clarify the spec for the flag...

Default Chart name (directory and in Chart.yaml) to application name which is currently used for the helm release name, which itself is defaulted to the dirname.

Application name can be overridden by `--app`, which would also affect the Chart name.

The `--name` option would not be needed in this scenario as `--app` covers the use case.

Correct?

**Comment by bacongobbler** [comment]
We've actually been talking about making the chart name the same as what's defined by `draft create --app` (or through the implied app name), so there would be no need for a --name flag, so you are correct.

**Comment by bacongobbler** [comment]
To be 100% clear, here's what the changes requested are:

Current implementation:

```
><> pwd
/home/bacongobbler/go/src/github.com/Azure/draft/examples/example-python
><> draft create
--> Draft detected Python (97.267760%)
--> Ready to sail
><> ls charts/
python
><> cat charts/python/Chart.yaml
apiVersion: v1
description: A Helm chart for Kubernetes
name: python
version: v0.1.0
```

Proposed change:

```
><> pwd
/home/bacongobbler/go/src/github.com/Azure/draft/examples/example-python
><> draft create
--> Draft detected Python (97.267760%)
--> Ready to sail
><> ls charts/
example-python
><> cat charts/example-python/Chart.yaml
apiVersion: v1
description: A Helm chart for Kubernetes
name: example-python
version: v0.1.0
```
