### ISSUE TITLE
Draft init doesn't work on windows bash

### ISSUE THREAD

**Issue by idelix** [Azure/draft#502]
I'm trying to run draft init on windows bash (Windows Subsystem for Linux) but getting the plugins error:

Installation of draft:

curl -O https://azuredraft.blob.core.windows.net/draft/draft-canary-linux-amd64.tar.gz
tar -xzf draft-canary-linux-amd64.tar.gz
sudo mv linux-amd64/draft /usr/local/bin

Running Draft init:

[debug] installing plugin from https://github.com/Azure/draft-pack-repo
[debug] cloning https://github.com/Azure/draft-pack-repo to /home/idelix/.draft/cache/plugins/https-github.com-Azure-draft-pack-repo
Error: Unable to get repository: : fork/exec /usr/bin/git: invalid argument

**Comment by bacongobbler** [comment]
It looks like git is not installed. We’ll have to add that to the installation guide. :) would you mind installing git and try again?

**Comment by idelix** [comment]
Thanks for fast response.

Unfortunately I get this command even with git installed, here is more details:

Windows build: Version 1607 (OS Build 14393.2035)

Actions:

reinstall bash on windows: lxrun /uninstall /full

bash

cd /home/idelix

sudo apt-get update

sudo apt-get install git

wget https://azuredraft.blob.core.windows.net/draft/draft-canary-linux-amd64.tar.gz

tar -zxvf draft-canary-linux-amd64.tar.gz

sudo mv linux-amd64/draft /usr/local/bin

draft init --debug

Installing default plugins...
[debug] installing plugin from https://github.com/Azure/draft-pack-repo
[debug] cloning https://github.com/Azure/draft-pack-repo to /home/idelix/.draft/cache/plugins/https-github.com-Azure-dra
ft-pack-repo
Error: Unable to get repository: : fork/exec /usr/bin/git: invalid argument

**Comment by bacongobbler** [comment]
Hmm. Oh well, it was worth a shot :) I’ll try to troubleshoot tomorrow when I’m in the office, but the code here is failing when trying to fetch the draft-pack-repo plugin from GitHub. If you want to start pouring over the source code to find the error yourself, you can find that here: https://github.com/Azure/draft/blob/master/pkg/plugin/installer/vcs_installer.go

Hope this helps!

**Comment by idelix** [comment]
Thanks, I'm back on Thursday so will try check it then worst case I will install ubuntu on hyperv and setup the draft in there, although would be nice to have it in bash for windows.

**Comment by jskulavik** [comment]
@bacongobbler, I'm running into this exact same issue both on Ubuntu bash for Windows, and the Azure Cloud Shell (full Ubuntu).  Git is fine across the board, as is Helm.  I'll look at the vcs_installer.go file and see if anything jumps out

**Comment by jskulavik** [comment]
Error on bash for Windows:  `Error: Unable to get repository: : fork/exec /usr/bin/git: invalid argument`

Error on cloud shell: `Error: fork/exec /home/[user]/.draft/draft-pack-repo/bin/pack-repo: no such file or directory`

**Comment by idelix** [comment]
I haven't found out what was cause of the problem but at the end it worked when I reinstalled os with the windows 10 version 1709 (os build 16299.192) then installed bash for win using this article https://docs.microsoft.com/en-gb/windows/wsl/install-win10.

**Comment by bacongobbler** [comment]
OK I'm going to close this as resolved then :)

@jskulavik if you're still having issues could you open a new ticket? Your errors seem like a different issue so we should track that separately anyways. Thanks!
