### ISSUE TITLE
No information is provided when a releasing an application fails

### ISSUE THREAD

**Issue by thedrow** [Azure/draft#538]
I have no idea why the release failed. All the output I get is:
```
Draft Up Started: 'myproject'
myproject: Building Docker Image: SUCCESS ⚓  (0.9833s)
myproject: Pushing Docker Image: SUCCESS ⚓  (16.0037s)
myproject: Releasing Application: FAIL ❌  (0.5042s)
myproject: Build ID: 01C5VA8VJXXQ2DC9GQ7ZJDV2QH
```
Even with debug log on there's no way to tell why a release failed.

**Comment by bacongobbler** [comment]
Check `draft logs` to see why the build failed. We should probably add that to the CLI output as a follow-up for the user. :)
