### ISSUE TITLE
buildApp: pushImg error: unauthorized: Not Authorized

### ISSUE THREAD

**Issue by appsuwear** [Azure/draft#543]
Just created a draft "draft create" on a simple go application.
Do you know how to set user and password for, in this case google container reg. gcr.io?

```
draft up                
Draft Up Started: 'draft'
draft: Building Docker Image: SUCCESS ⚓  (16.0303s)
draft: Pushing Docker Image: FAIL ❌  (1.0043s)
draft: Build ID: 01C6K0TQV8MB4DNP6H6G8H7EY7
    
    draft logs
    buildApp: pushImg error: unauthorized: Not Authorized.
```

draft version

```
draft version
Client: &version.Version{SemVer:"v0.10.1", GitCommit:"486291360aeffa2fe0a131fbf0b4f3c601056b16", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v0.10.1", GitCommit:"486291360aeffa2fe0a131fbf0b4f3c601056b16", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
Hey @appsuwear! Google Container Registry support is being discussed over at #355. We'd love your feedback there!

Because an issue for GCR support already exists, I'm going to go ahead and close this as a duplicate. Thanks!
