### ISSUE TITLE
If tiller runs with tls draft init command doesn't work

### ISSUE THREAD

**Issue by pushrbx** [Azure/draft#544]
When I try to install draft on my cluster which has a tiller configured to use TLS I get the following error:
```
2018/02/20 23:41:58 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
Error: error installing Draft: transport is closing
```
Does `draft init` support a helm installation with TLS?

**Comment by fibonacci1729** [comment]
#548

**Comment by bacongobbler** [comment]
good catch, @fibonacci1729. Let's close this issue in favour of #548. :)
