### ISSUE TITLE
[Wish] Ability to add insecure registry in draft setup

### ISSUE THREAD

**Issue by stephenpope** [Azure/draft#546]
(Apologies if this is possible already and I have missed something in the docs)

Example: I am using the latest `minikube` (vm-driver=none) but the IP range my registry is assigned is `10.97.*.*` which falls outside of the ones currently defined.

It would be nice to have the ability to pass my own insecure registry ranges to `Draft` when I am installing it.  (Currently I have to go in and edit the `deployment.yaml` manually)

**Comment by bacongobbler** [comment]
Hey @stephenpope, this is currently not possible, but we'd happily accept a PR to make this happen!
