### ISSUE TITLE
RPC target on Makefile fails

### ISSUE THREAD

**Issue by radu-matei** [Azure/draft#555]
[The Makefile in `pkg/rpc/Makefile`](https://github.com/Azure/draft/blob/master/pkg/rpc/Makefile#L1-L3) makes some assumptions about the location of some dependencies that are not guaranteed to be found there.

As a result, `make rpc` fails.

**Comment by michelleN** [comment]
Yeah, I'm getting this issue too. Specifically on `$(HOME)/src/protobuf/include` not being present. @fibonacci1729 - you have any guidance for us on how we should proceed here?
