### ISSUE TITLE
Java Play app not detected

### ISSUE THREAD

**Issue by puneet101** [Azure/draft#556]
Puneets-MacBook-Pro-3:Control puneet$  draft create
Error: no languages were detected

Are Java Play apps supported? 

Is there a plan to auto-import Heroku Java apps with existing Procfiles?

Thanks,
Puneet

**Comment by puneet101** [comment]
We use sbt to compile the project and have a build.sbt file in the main folder.

**Comment by michelleN** [comment]
Hey @puneet101 - Looks like there is not a pack for Java Play apps specifically. You can view all of the available packs [here](https://github.com/Azure/draft/tree/master/packs). There are two things you can do in this scenario: 

1. You can place your own Dockerfile in the directory and then run `draft create`. That should detect java and give you a `chart` as well as a `draft.toml` file which are the pieces you need to deploy your app to Kubernetes using draft. If the language auto-detection doesn't work, you can pass in the pack you want to use using `draft create --pack java`
OR
2. You can create your own Java Play pack using [these instructions ](https://github.com/Azure/draft/blob/master/docs/reference/dep-003.md#the-pack-structure)and host them in [your own repo](https://github.com/Azure/draft/blob/master/docs/reference/dep-004.md#creating-a-pack-repository) or contribute them to this repo.

**Comment by puneet101** [comment]
Thanks!

**Comment by jgleonard** [comment]
@puneet101 did you end up creating a pack to use?  If so, I'd love to take a look.
