### ISSUE TITLE
Feature request: support skipping pushing image

### ISSUE THREAD

**Issue by bjornmagnusson** [Azure/draft#569]
Draft pushing the Docker image at every rebuild. When using Docker for WIndows/Mac (or even Minikube as the Docker host) this is a bit unnecessary as the locally built Docker images are available to the cluster already.

Request:
Add flag to skip pushing the image and/or auto-detect that the environment is Docker for Windows/Mac. Possible with "kubectl config current-context"

Why:
Less steps means faster turnaround and feedback for developer

**Comment by bacongobbler** [comment]
Hey @bjornmagnusson! Because this has already been asked at #432 I'm going to close this as a duplicate. Please feel free to read through the discussion and add your thoughts there. Thanks!
