### ISSUE TITLE
Release binary of v0.11.0-rc1 for macOS is 404

### ISSUE THREAD

**Issue by mumoshu** [Azure/draft#570]
@michelleN Hi, thank you for maintaining this great project 👍 

The link to the macOS binary is 404 due to a typo in the URL.
You will probably want to fix `v0.11-0` to `v0.11.0`.

BEFORE: `https://azuredraft.blob.core.windows.net/draft/draft-v0.11-0-rc1-darwin-amd64.tar.gz`
AFTER: `https://azuredraft.blob.core.windows.net/draft/draft-v0.11.0-rc1-darwin-amd64.tar.gz`

**Comment by bacongobbler** [comment]
Hey! Thanks for the heads up. I noticed this earlier today and tried to fix it but made the typo. Thanks for pointing it out!
