### ISSUE TITLE
Streaming logs for draftd-less Draft

### ISSUE THREAD

**Issue by radu-matei** [Azure/draft#584]
As I mentioned in #573, it would be nice to have streaming logs when doing `draft up`

**Comment by squillace** [comment]
Are you talking about build logs? Have no problem with a switch in settings or flag, but I suggest streaming logs are a fetish. Or different logs?

**Comment by squillace** [comment]
On the other hand, maybe my anti fetish is a fetish? Hard to know.

**Comment by radu-matei** [comment]
I don't know, most people I've shown Draft question what happens during the build phase - it's more an anti anti fetish.. 😄

**Comment by radu-matei** [comment]
Sounds great :)

**Comment by radu-matei** [comment]
Closing as `draft logs` is really nice to use.

**Comment by radu-matei** [comment]
cc @bacongobbler

**Comment by radu-matei** [comment]
Closing this as the `draft logs --tail` fixes the issue
