### ISSUE TITLE
[Draft .12]: connection "sticks open" across clusters, terminals

### ISSUE THREAD

**Issue by squillace** [Azure/draft#624]
repeatedly running Draft against minikube, with and without registry config, and then switching to AKS westus2 cluster. Ubuntu 16.04, Unity/Terminology as terminal/shell is oh my zsh.

CTRL-C does not terminate the "connection". restarting terminal doesn't shake it, restarting minikube doesn't shake it. That's one tough connection. It'd be fine if it was accurate and it restated what port the active connection was on -- but I don't believe it's true. Does not fall over if I change clusters.

![image](https://user-images.githubusercontent.com/1422718/38008048-62c86c00-3201-11e8-8d91-d5ae46df4be9.png)

**Comment by squillace** [comment]
Update: I'm able to torch the connection if I destroy the artifacts in the app and rerun `draft create`. Then the connection recreates successfully.

**Comment by radu-matei** [comment]
@squillace - do you still see the issue?
Can we close this?

Thanks!

**Comment by bacongobbler** [comment]
closing until otherwise instructed to re-open. :)
