### ISSUE TITLE
Draft up should pipe logs immediately to the log file

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#628]
During longer builds, in another terminal I find myself wanting to inspect the logs from the current build. Because we only write to the log file once the build has finished, the user doesn't know about the build status until it finishes. I'd love for us to pipe these logs straight to the log file rather than through a buffer.

**Comment by bacongobbler** [comment]
Also see #584 for another scenario

**Comment by fibonacci1729** [comment]
closed by #638
