### ISSUE TITLE
draft delete --environment=x doesn't work

### ISSUE THREAD

**Issue by robertstarmer** [Azure/draft#646]
I can delete the environment deployments with helm, but it'd be nice to be able to use the same tool for create/delete.

**Comment by radu-matei** [comment]
Hi, @robertstarmer!
As a temporary workaround, you can execute `draft delete <app>`.

In any case, I started working on `draft delete --environment` - is this the UX you're looking for?

**Comment by radu-matei** [comment]
@robertstarmer - let us know if this solves your use case.

Thanks!

**Comment by robertstarmer** [comment]
Yep, that's what I was looking for!  Sorry about the delayed response
