### ISSUE TITLE
Be able to list available packs

### ISSUE THREAD

**Issue by technosophos** [Azure/draft#648]
So yesterday I added some pack repos. But now I'm not clear how I go find out what packs are available in those repos. It would be nice to have a command to do that.

If packs are to be a central selling point for Draft, I would suggest making this a core feature rather than a plugin.

**Comment by fibonacci1729** [comment]
Albeit a plugin, is `draft pack-repo list` insufficient?

**Comment by bacongobbler** [comment]
`draft pack-repo list` lists pack repositories, but not the packs within those pack repos :)

**Comment by bacongobbler** [comment]
implemented in #676
