### ISSUE TITLE
draft create enters infinite loop on Windows

### ISSUE THREAD

**Issue by alexpilotti** [Azure/draft#650]
Running "_draft create_" on Windows hangs. Adding "_--debug_" shows that it loops endlessly through the packs.

Workaround: specify the desired pack name / path:

 `draft create -p "github.com\Azure\draft\packs\csharp"`

**Comment by radu-matei** [comment]
Hi, @alexpilotti!
I currently don't have access to a Window machine, but first thing I will do is replace `path.Join` from
 https://github.com/Azure/draft/blob/master/cmd/draft/create.go#L192 with `filepath.Join`

Let me know if you have a chance to try this before I do.

Thanks!

**Comment by radu-matei** [comment]
Thanks, @bacongobbler!

@alexpilotti - let us know if the issue is solved now.
