### ISSUE TITLE
`draft init --dry-run --debug` is somewhat useless

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#7]
It's *sorta* useful in the fact that the information about the chart is displayed, but the actual information is not truly useful outside of debugging the chart. It would be cool if this could be improved to make it load-able via `helm install`, dumped to a .tar.gz or something.

**Comment by frodopwns** [comment]
I'd be happy to take a stab at this!

**Comment by bacongobbler** [comment]
closing as irrelevant in master.
