### ISSUE TITLE
draft init fails on Windows

### ISSUE THREAD

**Issue by radu-matei** [Azure/draft#707]
Deleted the `.draft` directory, `draft version` below:

```shell
draft version
&version.Version{SemVer:"v0.14.0", GitCommit:"e7a92f6b2f05a23f4cd9cc15fc24eb98d628e5d7", GitTreeState:"clean"}
```

When doing `draft init`:

```
draft init
Installing default plugins...
```

After this step the terminal (Powershell or CMD) quits entirely - it cloned `draft-pack-repo` in the plugin directory. If I try to execute the `scripts\get.ps1` manually, it's denied because of the execution policy.

> If I'm not missing anything, we probably should add a note on the execution policy in the docs for `draft init`, then switch it back! [Link to the docs for execution policy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6)

If I set the execution policy to `Unrestricted` and execute the get script manually:

```shell
.\get.ps1
Downloading https://github.com/draftcreate/draft-pack-repo/releases/download/canary/pack-repo-vcanary-windows-amd64.zip
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At C:\Users\radum\.draft\plugins\draft-pack-repo\scripts\get.ps1:13 char:1
+ (new-object System.Net.WebClient).DownloadFile($url, $file)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Preparing to install into \plugins\draft-pack-repo\bin
Expand-Archive : The path 'C:\Users\radum\AppData\Local\Temp\pack-repo-vcanary-windows-amd64.zip' either does not
exist or is not a valid file system path.
At C:\Users\radum\.draft\plugins\draft-pack-repo\scripts\get.ps1:20 char:1
+ Expand-Archive -Path "$file" -DestinationPath "$tempDir" -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\radum\...ndows-amd64.zip:String) [Expand-Archive], InvalidOpe
   rationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

Move-Item : Cannot find path 'C:\Users\radum\AppData\Local\Temp\pack-repo\windows-amd64\pack-repo.exe' because it does
not exist.
At C:\Users\radum\.draft\plugins\draft-pack-repo\scripts\get.ps1:22 char:1
+ Move-Item -Path "$tempDir\windows-amd64\$name.exe" -Destination "$bin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\radum\...4\pack-repo.exe:String) [Move-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

```

This seems to be because of the [deprecation of `TLSv1/TLSv1.1` by GitHub](https://githubengineering.com/crypto-removal-notice/)

To check the (what I think is the default) security protocol:

```shell
[Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls
```
appears to be `Tls`, which I think is `TLSv1`.

If you go further and set the protocol for this session to be `TLSv1.2`:

```shell
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
```
and try to execute the script again - not `draft init`, as the command above is only valid for the current session:

```shell
Downloading https://github.com/draftcreate/draft-pack-repo/releases/download/canary/pack-repo-vcanary-windows-amd64.zip
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: The connection was closed unexpectedly."
At C:\Users\radum\.draft\plugins\draft-pack-repo\scripts\get.ps1:13 char:1
+ (new-object System.Net.WebClient).DownloadFile($url, $file)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

```

The same error - `The request was aborted: The connection was closed unexpectedly.` also appears if I switch to `Invoke-WebRequest`

At this point I've started looking at [what version of the .NET Framework I have installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) - .NET Framework 4.7.1, which comes by default with Windows 10 Fall Creators Update.

I added all supported protocols:

```shell
$AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
[System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols

[Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls, Tls11, Tls12
```
Still the same error on a different network, and on another Windows PC.

This is annoying.

**Comment by idelix** [comment]
I'm having the same issue on Windows

**Comment by radu-matei** [comment]
For the record, you can still use Draft, just the pack repo functionality is missing, and you can manually add the executable:

- download the release from this url - https://github.com/draftcreate/draft-pack-repo/releases/download/v0.4.1/pack-repo-v0.4.1-windows-amd64.zip

- unzip it and copy the executable in `DRAFT_HOME\plugins\draft-pack-repo\bin`

**Comment by bacongobbler** [comment]
This workaround works for me on Windows:

```
C:\Users\mafishe> draft init
C:\Users\mafishe> draft plugin remove pack-repo
C:\Users\mafishe> draft plugin install https://github.com/draftcreate/draft-pack-repo --version master
C:\Users\mafishe> draft init
Installing default plugins...Installation of default plugins complete
Installing default pack repositories...
Installing pack repo from https://github.com/Azure/draft
Installed pack repository github.com/Azure/draft
Installation of default pack repositories complete
$DRAFT_HOME has been configured at C:\Users\mafishe\.draft.
Happy Sailing
```

Honestly, the best move forward is to implement #688. The current install process for plugins is proving to be very fragile, and we were planning on doing that work anyways in 0.15. Rather than coming up with yet another crutch, we should just bite the bullet and get the work done.
