### ISSUE TITLE
Provide documentation about exposed YAML variables

### ISSUE THREAD

**Issue by EvanDarwin** [Azure/draft#716]
I've been struggling to configure environments correctly with draft, since I can't use `helm` directly and there doesn't seem to be any documentation anywhere about what values are exposed on the `.Draft` template variable in the helm YAML files. 

Are they available anywhere?

**Comment by radu-matei** [comment]
Hi, @EvanDarwin!

Among the values injected by Draft (I hope I'm not missing any):

- `image.repository`
- `image.tag`
- `buildID`
- `draft`

What are you trying to do?

**Comment by bacongobbler** [comment]
Yep! You can use `helm inspect values app_name` to get the live values injected by Draft, or see [DEP 002 - Draft Design](https://github.com/Azure/draft/blob/master/docs/reference/dep-002.md). :)

**Comment by EvanDarwin** [comment]
Awesome, thanks for the info @bacongobbler. Kubernetes is really complex and draft makes my life much easier!

Also sorry for making a new issue, but hopefully others will be able to find this info in Google now.

**Comment by EvanDarwin** [comment]
@radu-matei -- For some reason your post didn't appear for me earlier. I was trying to have a dynamic `Values.yaml` file that picked the correct value based on the configuration (as is possible here https://github.com/kubernetes/helm/issues/2620#issuecomment-314719592), but it looks like the environment isn't exposed by draft.
