### ISSUE TITLE
Allow charts in other directories

### ISSUE THREAD

**Issue by radu-matei** [Azure/draft#739]
Right now, if you have you chart in a directory other than `charts/`, you cannot use Draft.

**Comment by michelleN** [comment]
What would you like for the behavior to be? Can you give an example of your use case?

**Comment by radu-matei** [comment]
For example, the OSBA project has the chart under `contrib/k8s/charts/open-service-broker-azure`.

The first use case would be to specify in `draft.toml` the relative path that doesn't necessarily have to be under `charts/`.

(The other use case, which is a separate issue, would be to add in  `draft.toml` a remote chart - however that is tracked in #732 )

**Comment by michelleN** [comment]
gotchya yea that makes sense to me!
