### ISSUE TITLE
Progress messages garbled during "draft up" on Windows

### ISSUE THREAD

**Issue by mlgibbons** [Azure/draft#746]
When I run a "draft up" on Windows 7 I see garbled characters in both in CMD and PowerShell.

![image](https://user-images.githubusercontent.com/8548451/39954659-914d8c4a-55ba-11e8-948e-93610e42cd47.png)

![image](https://user-images.githubusercontent.com/8548451/39954661-9b82e0de-55ba-11e8-8432-35a838872507.png)

**Comment by mlgibbons** [comment]
Sure. Any tips on how to build draft on Windows 7? I've not used Go before but it's on my list of things to learn so happy to use this as a vehicle to do that.

**Comment by bacongobbler** [comment]
To be honest it's probably best to use the pre-compiled canary release instead. A lot of the development process centers around macOS/Linux as the development machine of choice.

If you'd like to use a pre-compiled release of Draft, you can use the canary releases to test this out :) Canary releases of the Draft client for Windows can be found here: https://azuredraft.blob.core.windows.net/draft/draft-canary-windows-amd64.zip

**Comment by mlgibbons** [comment]
Ah. I did wonder if cross-compiling was the normal way of doing Windows builds. 

Test looks good. Screenshot is below. 

One minor point to note is the square betweeen the "SUCCESS" and the timing which doesn;t quite look right.

![image](https://user-images.githubusercontent.com/8548451/39960258-613e3862-5617-11e8-809f-79a72ff2e2c8.png)

**Comment by bacongobbler** [comment]
Yeah that's the emojis which are being tracked in #304 so we can go ahead and close this :)
