### ISSUE TITLE
First run of "draft init" on Windows causes containing console window to close 

### ISSUE THREAD

**Issue by mlgibbons** [Azure/draft#747]
If I run "draft init" in a CMD console it closes the console on completion. This does not happen if run in a PowerShell console.

**Comment by bacongobbler** [comment]
This behaviour unfortunately is the default behaviour of CMD and PowerShell. When a command exits with a non-zero exit code, the terminal abruptly exits. See http://blog.danskingdom.com/keep-powershell-console-window-open-after-script-finishes-running/

I've had better behaviour with VSCode's integrated terminal, Hyper or Cmder as the terminal of choice. :)

**Comment by mlgibbons** [comment]
It only happens in Cmd though; not in PowerShell. I didn't see the RC as it had exited. I shall experiment a little more and try and get a bit more data.

**Comment by bacongobbler** [comment]
Without any logs I can't tell ya :) if you purge %userhome%\.draft and re-run `draft init` what do you see?

**Comment by mlgibbons** [comment]
By "see" you mean in the logs dir? It's empty. Even when using --debug; although that did spit more info out to console. Piped it to file (figuring maybe stdout was not being fully flushed to console before it closed) and saw this where p1 is the first init output and pi is the second.

C:\temp>type p
Installing default plugins...
Downloading https://azuredraft.blob.core.windows.net/draft/pack-repo-v0.4.2-windows-amd64.zip
Preparing to install into C:\Users\Mark\.draft\plugins\draft-pack-repo\bin
pack-repo installed into C:\Users\Mark\.draft\plugins\draft-pack-repo\bin\pack-repo.exe
Installed plugin: pack-repo
Installation of default plugins complete
Installing default pack repositories...
Installing pack repo from https://github.com/Azure/draft

C:\temp>type pi
Installing default plugins...
Installation of default plugins complete
Installing default pack repositories...
Installation of default pack repositories complete
$DRAFT_HOME has been configured at C:\Users\Mark\.draft.
Happy Sailing!

**Comment by radu-matei** [comment]
I think this is addressed by #717 
Could you please let us know if the problem still exists after that fix?

Thanks!

**Comment by bacongobbler** [comment]
Ah yes, this definitely looks like #717 :)

@mlgibbons if you want to verify that this is fixed in the canaries, the links to the canary releases can be found here: https://github.com/Azure/draft/blob/master/docs/install-minikube.md#install-draft :smile:

**Comment by radu-matei** [comment]
I just tested again on Windows and this indeed seems to be fixed.
Closing this, but feel free to reopen, @mlgibbons, if you encounter any other issues related to init on Windows!

Thanks!

**Comment by mlgibbons** [comment]
Radu. Excellent. Will do. Many thanks. Mark.
