### ISSUE TITLE
Skip pushing to registry as a per-environment setting

### ISSUE THREAD

**Issue by radu-matei** [Azure/draft#768]
Consider the environments:

- one local cluster (Docker for Mac / Minikube) - this doesn't need the image pushed to a registry
- one remote cluster - this needs the image pushed

Even if I explicitly set `registry = ""` in `draft.toml`, the global config gets picked up, and I have to go back and forth between setting `draft config set registry <registry>`  and `draft config unset registry` in order to get this to work.

How do we make sure we can easily switch between the two and still make sure we don't break things for people that rely on the global config (and don't really care about pushing the image)?

A specific flag `--skip-image-push`? I always like explicit behaviour rather than implicit.

**Comment by mootpt** [comment]
Added this in #848

**Comment by radu-matei** [comment]
closed in #848
