### ISSUE TITLE
tag and release 0.4.0

### ISSUE THREAD

**Issue by sgoings** [Azure/draft#77]
0.3.0 was built with support for Helm 2.3.* so a version bump of draft makes sense now that we're consuming Helm 2.4.* libraries.

**Comment by bacongobbler** [comment]
I'll close this out once we create a milestone for v0.4.0 with the rest of the stuff I'd like to get merged before we cut.

**Comment by bacongobbler** [comment]
There. I've filed a bunch of additional stuff for the [v0.4.0 milestone](https://github.com/Azure/draft/milestone/1) that I should be able to tackle today, then we can cut v0.4.0 later today or tomorrow.
