### ISSUE TITLE
Externalize packs

### ISSUE THREAD

**Issue by sgoings** [Azure/draft#78]
Currently packs are built into the draft binary. It'd be much nicer to download/install packs similar to the UX of `helm` plugins (`helm plugin install <url>`).

Externalizing packs would:
- better enable organizations to create, distribute, and drive internal standards
- drive a larger and more engaged pack curation community

**Comment by bacongobbler** [comment]
Somewhat a duplicate request of #2 as that ticket would handle such use cases.
