### ISSUE TITLE
CONTRIBUTING.md guideline file missing

### ISSUE THREAD

**Issue by zdeptawa** [Azure/draft#793]
I wasn't able to find a CONTRIBUTING.md file with contributing guidelines for Draft - I've usually seen them at the root of repositories. There is a 'contributing' folder in the draft repo, but no real contributing guidelines that I've found. Could we look at adding something?

**Comment by bacongobbler** [comment]
Yes that sounds like a great idea. I've actually started taking a stab at restructuring the documentation into a website in #770 that centralizes around a few core concepts including a contributing guide. We can reference to that in CONTRIBUTING.md once it's done. For now @raravena80's PR in #797 should be a good starting place to work on how we wanna shape the CONTRIBUTING docs.

Does that sound like something you'd be interested in influencing? :)

**Comment by zdeptawa** [comment]
@bacongobbler I'd love to help however I can! I see you have #801 open now to at least knock this issue out. Should we close it and follow up there? Thanks for your help here!

**Comment by sam-doordash** [comment]
This needs to be closed @bacongobbler - #801 sorted it.

**Comment by bacongobbler** [comment]
We generally close issues once the PR has been merged; that way if we need to close PRs in favour of another or back it out we can continue to track it here. Makes it easier to triage :)

**Comment by bacongobbler** [comment]
But yes once #801 is merged this issue will automatically close. :)
