### ISSUE TITLE
draft up failed due to Error parsing reference for example-java 

### ISSUE THREAD

**Issue by quantum-fusion** [Azure/draft#807]
The problem is that draft up will not build the image needed in order to connect to Kubernetes.  Although this worked in previous test case runs, it is unknown why this is causing a problem now.  

Therefore I have attached the test case here example-java.tar 

@bacongobbler @squillace See error in draft up , it is inconsistent behavior, and was not previously failing.

[example-java.tar.zip](https://github.com/Azure/draft/files/2065017/example-java.tar.zip)

draft up
Draft Up Started: 'example-java': 01CF0AGGV2MYE8EJVM5CTCXMDA
example-java: Building Docker Image: FAIL ❌  (1.0002s)
Inspect the logs with `draft logs 01CF0AGGV2MYE8EJVM5CTCXMDA`

MacBook-Pro-2:example-java $ draft logs 01CF0AGGV2MYE8EJVM5CTCXMDA
Step 1 : FROM maven:3.5-jdk-8 as BUILD
2018/06/02 09:20:43 error while building: Error parsing reference: "maven:3.5-jdk-8 as BUILD" is not a valid repository/tag

**Comment by bacongobbler** [comment]
what version of Docker are you using Draft with? IIRC the AS flag is a relatively newer flag and as such might not work with all versions of Docker.

**Comment by quantum-fusion** [comment]
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by quantum-fusion** [comment]
@bacongobbler see version of docker.

**Comment by bacongobbler** [comment]
odd. I just unpacked your example app and it works for me without any issues on `draft up`. I'm using 18.05.0-ce but that shouldn't make much of a difference.

**Comment by quantum-fusion** [comment]
MacBook-Pro:~/Desktop/Projects/draft/examples quantum-fusion$ cd example-java
MacBook-Pro:~/Desktop/Projects/draft/examples/example-java quantum-fusion$ ls
Dockerfile	draft.toml	src
charts		pom.xml		target
MacBook-Pro:~/Desktop/Projects/draft/examples/example-java quantum-fusion$ draft up
Draft Up Started: 'example-java': 01CFXJVZ3SYRF0KGNHM7MBAQPF
example-java: Building Docker Image: SUCCESS ⚓  (75.0260s)
example-java: Pushing Docker Image: SUCCESS ⚓  (13.4423s)
example-java: Releasing Application: SUCCESS ⚓  (2.4074s)
Inspect the logs with `draft logs 01CFXJVZ3SYRF0KGNHM7MBAQPF`
MacBook-Pro:~/Desktop/Projects/draft/examples/example-java quantum-fusion$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
MacBook-Pro:~/Desktop/Projects/draft/examples/example-java quantum-fusion$ draft connect
Connect to java:4567 on localhost:55296
[java]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[java]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[java]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[java]: == Spark has ignited ...
[java]: >> Listening on 0.0.0.0:4567

**Comment by quantum-fusion** [comment]
I did a complete and total uninstall of minikube and helm, which weren't shown here.

**Comment by quantum-fusion** [comment]
It resolved the issue.

**Comment by quantum-fusion** [comment]
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

minikube version
minikube version: v0.27.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
