### ISSUE TITLE
Build error: can't find Dockerfile if Dockerfile name is blank on Windows

### ISSUE THREAD

**Issue by itowlson** [Azure/draft#808]
On a Windows machine, using current HEAD, go into the `example-go` sample and run `draft create` followed by `draft up`.

`draft up` fails during the `Building Docker Image` stage, and the logs contain:

```
2018/06/04 11:08:34 error while building: Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
```

Changing the `dockerfile` line in `draft.toml` to contain the name `Dockerfile` works around this.  This issue appears to be introduced with #798, as reverting that change also fixes it.

**Comment by easauceda** [comment]
Affected by this on mac as well.
