### ISSUE TITLE
Generate Jenkins file

### ISSUE THREAD

**Issue by stevesloka** [Azure/draft#83]
It would be neat to also generate a Jenkinsfile to help with builds once out of the `draft` phase and into the `rookie` stage. Some tagging scheme would be cool as well to allow for versioned tags (e.g.  pushes to `master` branch).

Maybe this could be a new command like `draft shipit`.

**Comment by bacongobbler** [comment]
I feel like this is out of scope for draft core. While this project does bootstrap an app, it's specifically targeting kubernetes development and is not trying to enforce other forms of tooling to the user.

However, if someone were to write a plugin, that'd be a cool addon.

**Comment by plytro** [comment]
If we created a custom pack (in a fork right now) and had that custom pack create a Jenkinsfile, .travis.yml, circle.yml, etc would this be possible right now? After looking at a pack definition, this seems to be the case.

**Comment by bacongobbler** [comment]
I don't believe so, but feel free to give it a shot. I won't guarantee that would be covered under server though. We only intend to copy over the Dockerfile and chart/ directory, so that's probably unintentional behaviour.

**Comment by bacongobbler** [comment]
Yep. It only loads the chart and Dockerfile from the pack dir. See https://github.com/Azure/draft/blob/master/pkg/draft/pack/load.go#L13-L49

**Comment by bacongobbler** [comment]
Closing this out as something not going to be implemented in core, but if someone wants to write a plugin then we can add it to the docs.
