### ISSUE TITLE
help wanted: draft up failing with `invalid reference format`

### ISSUE THREAD

**Issue by nasreddineskandrani** [Azure/draft#830]
Hi,
I did a setup of `minikube` to get a ` kubernetes cluster` running locally like 2 days ago.
I used this repo that i forked: https://github.com/nasreddineskandrani/minions
I am able to see the deployment of this example minions java app in  ` kubernetes dashboard` and access the java app when i follow the steps from the README file of this repo.

Now when i try to use `draft` inside the same minions project (i want to streamline the dev cycle). 
as mentionned here: https://azure.microsoft.com/en-ca/blog/streamlining-kubernetes-development-with-draft/
When i reach the step: `draft up` i have an error (please check the image attach.)

![draftup_fail](https://user-images.githubusercontent.com/1953635/42178276-bc579d98-7dfd-11e8-86d3-985e82617b4e.png)

Question1
why **`draft up`** is failing with `...invalid reference format....`?

Question2
how i can debug this kind of errors?

Question3
Can someone tell me if with `draft up` it's right to expect a deployment to be done in the local kubernetes cluster and java app to be accessible?

**Comment by bjornmagnusson** [comment]
I tried that repo with draft, and seems to be working.
Draft Up Started: 'minions': 01CHEB1WBGQ76ZE0CZ1BMAY8GD
minions: Building Docker Image: SUCCESS ⚓  (167.0839s)
minions: Releasing Application: SUCCESS ⚓  (8.4211s)
Inspect the logs with `draft logs 01CHEB1WBGQ76ZE0CZ1BMAY8GD`

From your image it states "chart directory already exists". Maybe try removing it and try again?

**Comment by nasreddineskandrani** [comment]
I removed `chart` folder and retried => not working. I am using `docker toolbox` since i am in a desktop win10 Home Edition.
After executing `draft init`, `draft create`, `draft up` do i need to do something to target my local cluster in the generated files?

**Comment by bacongobbler** [comment]
Nope! Draft will use your existing kubeconfig (like kubectl) to target your cluster.

**Comment by bjornmagnusson** [comment]
Can you give us a output of draft logs <build>, exact command is stated during your draft up

**Comment by nasreddineskandrani** [comment]
the output is the last line of the printscreen i posted. Their is nothing more then that.
i am not at home for now. I need to retry it to night. 

One detail:
i have draft in a folder then i copy/pasted the minions example inside.
So i am running my draft commend from `/minions` folder like that `../draft init`, `../draft create` ... i didn't add the draft exec to the env path. But i am guessing this has nothing to do with the issue. I flagged it in case.

So if it's using the same file as my `kubectl create` how he know which one.
When i do the create with kubectl i do the commend `kubectl create -f file.yml`
i supply explicitly the file how draft knows which one he has to use to deploy?

**Comment by bjornmagnusson** [comment]
Draft does not use the yaml file available in the repo. Under the hood it uses the Helm Chart (collection of yaml files) created by the _draft create_ command, available in the charts folder.

But the failing step is the building of the Docker image, which is done before the deployment into the cluster. Somehow the docker image name being create is invalid / malformed (decided by Docker)

**Comment by bjornmagnusson** [comment]
Can you output the folder structure (for example with the use of tree) and the content of the draft.toml file?

**Comment by nasreddineskandrani** [comment]
draft.toml
```
[environments]
  [environments.development]
    name = "testtest"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""
chart = ""
```

PS C:\Users\anaetnas\Desktop\testtest> tree /f
Folder PATH listing
Volume serial number is 443F-4CD6
C:.
│   .dockerignore
│   .draft-tasks.toml
│   .draftignore
│   .gitignore
│   deploy-test-remote.yml
│   deploy-test.yml
│   Dockerfile
│   draft.exe
│   draft.toml
│   helm.exe
│   LICENSE
│   minion-army.yml
│   mvnw
│   mvnw.cmd
│   pom.xml
│   README.md
│
├───charts
│   └───java
│       │   .helmignore
│       │   Chart.yaml
│       │   values.yaml
│       │
│       ├───charts
│       └───templates
│               deployment.yaml
│               ingress.yaml
│               NOTES.txt
│               service.yaml
│               _helpers.tpl
│
└───src
    ├───main
    │   ├───java
    │   │   └───org
    │   │       └───minions
    │   │           └───demo
    │   │                   Application.java
    │   │                   Controller.java
    │   │                   MinionsLibrary.java
    │   │
    │   └───resources
    │           application.properties
    │
    └───test
        └───java
            └───org
                └───minions
                    └───demo
                            ApplicationTests.java

**Comment by bjornmagnusson** [comment]
OK, looks fine. Actually very hard to debug this.

@bacongobbler Is there any situation where the sha256 generated in Azure/draft/pkg/builder/builder.go could potentially be an empty string? Maybe in case of some kind of failure or windows quirk?
If that would be the case, then the image name would be testtest: which would cause the docker daemon to object with the above error message.

**Comment by bjornmagnusson** [comment]
Maybe even the full output of `draft config list`?

**Comment by nasreddineskandrani** [comment]
```
draft config get registry
```
output:
```
http://192.168.99.100:30000
```

```
draft up
```
output:
```
Draft Up Started: 'minions': 01CHKZ5ZW1N0DYMB0WE3T9THRC
minions: Building Docker Image: FAIL ❌  (1.0018s)
Inspect the logs with `draft logs 01CHKZ5ZW1N0DYMB0WE3T9THRC`
```

```
draft logs
```
output:
```
2018/07/04 20:58:57 error while building: Error response from daemon: invalid reference format
```

```
draft config list
```
output:
```
KEY             VALUE
registry        http://192.168.99.100:30000
```

**Comment by bacongobbler** [comment]
That's it. Remove the `http://` from the registry name and it should work.

**Comment by bacongobbler** [comment]
So it should be `draft config set registry 192.168.99.100:30000`

**Comment by nasreddineskandrani** [comment]
cool it's solved! the docker build is ok now!
 i don't really need to know why not the `http://` for now :) but if you can explain it or share a link about it, i am interested.
![image](https://user-images.githubusercontent.com/1953635/42355507-72579518-809b-11e8-8ca0-72ca6980a68a.png)

thanks you all
