### ISSUE TITLE
File changes made in pre-up task not included in builded image

### ISSUE THREAD

**Issue by Dm3Ch** [Azure/draft#833]
I've realised that when I change files in pre-up stage script, this changes not included into building container.

Is this normal?
Maybe we can add pre-build stage?

**Comment by Dm3Ch** [comment]
I'm using docker builder.
Draft version: `&version.Version{SemVer:"v0.15.0", GitCommit:"9d73889a1318a435d126bc5df846610d30cfbe7f", GitTreeState:"clean"}`
Docker Version:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
OS: `macOS High Sierra 10.13.5`

**Comment by bacongobbler** [comment]
This was fixed in https://github.com/Azure/draft/pull/812 and is available in the canary release. It'll be available in the next release as well :)

**Comment by Dm3Ch** [comment]
@bacongobbler Thank you a lot. :)

**Comment by bacongobbler** [comment]
Canary releases are linked here: https://github.com/Azure/draft/blob/master/docs/install-minikube.md#install-draft

**Comment by Dm3Ch** [comment]
Thank you
