### ISSUE TITLE
local files changes are not being deployed automatically

### ISSUE THREAD

**Issue by rnkhouse** [Azure/draft#842]
I ran this command: `draft up --auto-connect`

    Connect to javascript:8080 on localhost:59132
    [javascript]: server is listening on 8080
    [javascript]: /
    [javascript]: /favicon.ico
    [javascript]: /
    [javascript]: /favicon.ico
    Your connection is still active.
    Connect to javascript:8080 on localhost:59132

Application is up and running on azure domain. But, when I make some changes in file it's not changing in real time. I manually needs to run `draft up` in orderto see latest changes.
Please advice.

**Comment by bacongobbler** [comment]
Hi @rnkhouse! The watch feature is not enabled by default, and in fact in #341 I reported that it does not work at this time.

If you want to invoke `draft up` on file changes, I highly recommend having a look at VSCode's kubernetes extension here: https://github.com/Azure/vscode-kubernetes-tools/

Using that extension, you should be able to invoke `draft up` when a file is saved. If not, the [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extension may help.

Will that work for you?

**Comment by rnkhouse** [comment]
Cool. Thanks for the detailed guideline.

**Comment by bacongobbler** [comment]
cool. I'm gonna close this in favour of #341 so we consolidate similar tickets into one. Thanks for your interest in the project!
