### ISSUE TITLE
Each pack should have an example app (gradle missing)

### ISSUE THREAD

**Issue by bjornmagnusson** [Azure/draft#849]
There should be an example app available for every `pack`. This to enable easy verification of changes to packs and to be able to show how an pack should be used.

Realized with #838 that there is no example app available for gradle.

@michelleN I think this is the reason for your "error" when trying the gradle pack with example-java (only maven build script) :) .

**Comment by bacongobbler** [comment]
@fiunchinho do you have a sample app for the gradle pack introduced in #170?
