### ISSUE TITLE
Create public Slack channel

### ISSUE THREAD

**Issue by bacongobbler** [Azure/draft#85]
Requested from twitter: https://twitter.com/elimallon/status/870086003809173504

@sgoings do we have the ability for something like creating a public azurecontainers.slack.com to host these channels?

**Comment by ultimateboy** [comment]
I'd also recommend just using the kubernetes slack. Anybody can create new channels there.

**Comment by bacongobbler** [comment]
Apparently not any more. I will contact someone and see if we can create those channels.

**Comment by bacongobbler** [comment]
#draft-users and #draft-dev are now up at kubernetes.slack.com.

**Comment by bacongobbler** [comment]
re-opening so we can document this in the README.
