### ISSUE TITLE
Error: exec: "C:\\Users\\username\\.draft\\plugins\\draft-pack-repo/bin/pack-repo": file does not exist

### ISSUE THREAD

**Issue by rnkhouse** [Azure/draft#852]
Getting below error on `draft init`:

>Error: exec: "C:\\Users\\ronak\\.draft\\plugins\\draft-pack-repo/bin/pack-repo": file does not exist

**Comment by bacongobbler** [comment]
@rnkhouse what's the output of `draft version`?

**Comment by rnkhouse** [comment]
>&version.Version{SemVer:"v0.15.0", GitCommit:"9d73889a1318a435d126bc5df846610d30cfbe7f", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
I can't seem to reproduce. If you can provide some steps on how you got to that point, that would be helpful. Try removing `~/.draft` and see if the problem persists.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

><> draft version
&version.Version{SemVer:"v0.15.0", GitCommit:"9d73889a1318a435d126bc5df846610d30cfbe7f", GitTreeState:"clean"}
><> draft init
Installing default plugins...
Downloading https://azuredraft.blob.core.windows.net/draft/pack-repo-v0.4.2-windows-amd64.zip
Preparing to install into C:\Users\mafishe\.draft\plugins\draft-pack-repo\bin
pack-repo installed into C:\Users\mafishe\.draft\plugins\draft-pack-repo\bin\pack-repo.exe
Installed plugin: pack-repo
Installation of default plugins complete
Installing default pack repositories...
Installing pack repo from https://github.com/Azure/draft
Installed pack repository github.com/Azure/draft
Installation of default pack repositories complete
$DRAFT_HOME has been configured at C:\Users\mafishe\.draft.
Happy Sailing!
```

**Comment by rnkhouse** [comment]
I tried removing `.draft` and it was working. but, I don't know what causes this error.

**Comment by bacongobbler** [comment]
great! It was probably an older version of the plugin was installed on your system. I'm going to close this as resolved but please feel free to re-open if this persists. Thanks!
