### ISSUE TITLE
Error: unknown flag: --skip-image-push

### ISSUE THREAD

**Issue by igsys** [Azure/draft#867]
When I typed "draft up --skip-image-push", I received this error:

Error: unknown flag: --skip-image-push

It's clearly in the source code, I wonder what happened.

**Comment by bacongobbler** [comment]
What's the output of `draft version`?

**Comment by igsys** [comment]
@bacongobbler I did a "draft version", here's the output:

&version.Version{SemVer:"v0.15.0", GitCommit:"...", GitTreeState:"clean"}

**Comment by igsys** [comment]
@bacongobbler Hi, I just tried the latest version v0.16.0, downloaded the OSX binary and copied to /usr/local/bin/draft.  It still gives me the same error.  Here's the "draft version" output:

version.Version{SemVer:"v0.16.0", GitCommit:"...", GitTreeState:"dirty"}

**Comment by bacongobbler** [comment]
looks like that flag only exists in master, as it's not there in the v0.16.0 tag. #848 introduced the feature. I'd suggest trying the canary release if you're interested in trying out that feature. :)

**Comment by bacongobbler** [comment]
Canary links can be found here: https://github.com/Azure/draft/blob/31ef4b18470305502275191d6532214e43814840/docs/install-minikube.md#install-draft

Thanks!

**Comment by igsys** [comment]
@bacongobbler I see some good uses for this flag, if it can be made into the next release, that would be awesome!!  Thanks for answers.
