### ISSUE TITLE
How do i switch to a different registry?

### ISSUE THREAD

**Issue by linsun** [Azure/draft#90]
I have configured to use docker hub but wanted to try a different registry.  I can't figure out how to do that other than I got "Warning: Draftd is already installed in the cluster." when I run the `draft init` cmd with my new registry config.

**Comment by bacongobbler** [comment]
Using `draft init --upgrade --set` should work. :)

**Comment by bacongobbler** [comment]
Alternatively you can also run `helm delete --purge draft` and run `draft init` again.

Let me know if these help!

**Comment by linsun** [comment]
thank you, --upgrade flag works!

**Comment by ultimateboy** [comment]
Closing the issue. Please re-open if you still need help adjusting the registry!
