### ISSUE TITLE
Draft create should check for draft init

### ISSUE THREAD

**Issue by razfriman** [Azure/draft#925]
I tried to create a draft for my project. after doing a fresh `brew` install of draft.
My first error was 
> Error: no languages were detected

So I forced the language to `csharp`. Then I see:
> Error: No packs found with name csharp

Had to go into the docs to see that you need to first run`draft init` to get the default plugins.

It would be nice for draft to do a check for this, or update the message to tell you that you forgot to init it

**Comment by bacongobbler** [comment]
duplicate of #900.
