### ISSUE TITLE
Will the support for draft is going to get over?

### ISSUE THREAD

**Issue by Sam123ben** [Azure/draft#938]
Hi, I liked the way draft is but it seems from last 6 or 7 months there are no active development done on it and so I am bit skeptical to use as I am not sure if it will be supported and that it will be released anytime soon?

Thanks

**Comment by riker09** [comment]
A little confusing title (at least it was not fully clear to me) but yeah, it adresses one of my two main concerns:

1. Is this project actively maintained? Can I safely invest my time in it?
2. Will there be support for Helm v3 and if so, when will it be ready? See #944 #943 #915

**Comment by bacongobbler** [comment]
See #957.
