### ISSUE TITLE
draft up with monorepo

### ISSUE THREAD

**Issue by gavinwilliams** [Azure/draft#945]
I've been scratching my head for the past week on how I can use Draft in a mono repo. Has anybody got any advice on this?

At the moment I have a directory structure like this.

/gateway
---/charts
/services
 --/service-1
     -/charts
 --/service-2
     -/charts
 --/service-3
     -/charts

Ideally I want to bring up all of these services during development from a single command and monitor their logs in one log stream rather than have to run draft up and have 4 terminal tabs open. I can do this out of the box using Skaffold.

I'm starting to think that I need to use Skaffold for this functionality and then use Helm to package up my service.

**Comment by riker09** [comment]
Possibly duplicate of #902?

**Comment by bacongobbler** [comment]
yep. thanks.
