### ISSUE TITLE
Converting a set of packfiles into a defaultpacks/*.go

### ISSUE THREAD

**Issue by nomisbeme** [Azure/draft#95]
I have a working pack (under ~/.draft/packs) and I'd like a convenient way to generate the corresponding defaultpacks/*.go boilerplate (or eliminate the need for them.)

**Comment by bacongobbler** [comment]
Can you elaborate more on this? I'm not sure I quite understand.

**Comment by ultimateboy** [comment]
First of all, it's awesome to hear that you've made your own pack! Out of curiosity, for what language is the pack you created?

As you've noticed, the defaultpacks are hardcoded at this point in time. We are hoping to implement a draft packs manager plugin at some time in the future which will probably change how we handle the defaultpacks: https://github.com/Azure/draft/issues/2

At this time, there's no convenient way to generate the .go boilerplate code for defaultpacks. If you need help converting your pack into a defaultpack for a PR, please open another issue and we'll help you out!

**Comment by nomisbeme** [comment]
I'm working on cleaning up my pack for Swift:
http://asciinema.org/a/aqj9x08jy0dj

@technosophos was working on the hardcoding of default packs last night at hackfest last night. He asked me to create this issue so we could track the work.

**Comment by technosophos** [comment]
I am working on a `go-bindata`-based implementation of what is there so that we can lower the barrier for maintaining the existing packs.

**Comment by nomisbeme** [comment]
Awesome, happy to give that a whirl when it's ready.
I sorted out my container image issues this morning so that's my last dependency on a PR for https://github.com/Azure/draft/issues/96
