### ISSUE TITLE
This project is no longer being actively developed or maintained?

### ISSUE THREAD

**Issue by keiransteele** [Azure/draft#957]
It appears that this project is dead, it would be good if this is noted if this is the case so we can move to something like Skaffold. There has been no real development work for all of 2019.

**Comment by cdeevfrr** [comment]
Bumping this - any confirmation that the project is dead? It still seems to be.

**Comment by cabrinoob** [comment]
Bumping this - any confirmation that the project is dead? It still seems to be.

**Comment by thatarchguy** [comment]
https://github.com/Azure/draft/issues/958#issuecomment-577400746

**Comment by thclark** [comment]
Agreed. A little 'unmaintained' note in the readme would've saved me the last hour and a half trying this out. FFS.

**Comment by bacongobbler** [comment]
Apologies for the delay on a response. Right now, our team has been re-allocated to other projects (Helm 3 being one of them) and we don't have the time to move Draft further than where it is at the moment. I hope we can get back to it at some point. We've clearly heard from the community that the model Draft provides is a very compelling story, and I wouldn't be surprised if there's some renewed initiative in the future.

In the meantime, I'm more than happy to answer questions about the project and its architecture. Please feel free to reach out at #draft-users or #draft-dev in the Kubernetes slack channel.

I'm going to close this as answered. Thanks for your feedback everyone.

**Comment by gavinwilliams** [comment]
If anyone stumbles upon this, I'm using devspace.sh. It's pretty amazing, has the same features as skaffold.sh (and then some) but isn't biased towards any particular platform.

I'm not affiliated with devspace.sh, I just genuinely think it's an awesome product, was using skaffold before I was recommended this by a friend.
