### ISSUE TITLE
Provide (or document) a way to delete Draft from a cluster

### ISSUE THREAD

**Issue by DazWilkin** [Azure/draft#97]
First time through installing Draft, I misconfigured the repo.

Subsequent attempts to revise the configuration by repeating `draft init` (appear to have) failed.

I tried `helm list` and `helm delete draft` to no avail.

Recommend:
Providing (or documenting) a way to delete draft or reconfigure it

**Comment by linsun** [comment]
try ```draft init --upgrade ``` (this is not obvious to me either)

**Comment by DazWilkin** [comment]
Thanks!

I did but think that didn't work for me either.

I'd borked the repository settings and this did not appear (may be incorrect) to correct them.

**Comment by bacongobbler** [comment]
You can do `helm delete --purge draft` to delete the helm chart and try again.
