### ISSUE TITLE
Please add support for Gradle to the Java pack

### ISSUE THREAD

**Issue by plombardi89** [Azure/draft#98]
It's the 2nd most popular build system in JVM land and often preferred for newer projects.

**Comment by bjoernstuetztss** [comment]
+1 
I do agree, would be quite important, thanks for the issue!

**Comment by bacongobbler** [comment]
If anyone wants to take this on, it's relatively simple to create a new pack: https://github.com/Azure/draft/tree/master/packs

An [example app](https://github.com/Azure/draft/tree/master/examples) to go with the pack would also be appreciated.

**Comment by fiunchinho** [comment]
This has been fixed as per #170

**Comment by plombardi89** [comment]
Thanks... I'll try it out soon!
